"use client"

import { useEffect, useMemo, useReducer, useState } from "react"
import { Beaker, CheckCircle2, Clipboard, Loader2, Search, X, XCircle } from "lucide-react"
import { supabase } from "@/lib/supabase"
import type { Screen } from "@/lib/types"
import type { GameCard as GameCardType, OfficialCardType, Rarity } from "@/lib/game-data"
import { GameCard } from "@/components/game/game-card"

type CatalogCard={id:string;code:string;name:string;image_url:string|null;element:OfficialCardType;rarity:Rarity;card_type:string;base_power:number;base_max_life:number;effect_mana_cost:number;effect_text:string|null}
type Scenario={test_id:string;card_id:string;card_name:string;effect_code:string;action_type:"activate_effect"|"declare_attack";objective:string;required_mana:number;before:{audited_card:{name:string;power:number;life:number;zone:string};practice_dummy:{name:string;power:number;life:number;rarity:string;zone:string};enemy_deck_count:number;player_hand_count:number};status:"ready"}
type Result={success:boolean;approved:boolean;status:string;effect_code:string;message:string;before:Scenario["before"];after:Scenario["before"];proof:Record<string,unknown>;reason?:string}
type State={scenario:Scenario|null;result:Result|null;phase:"catalog"|"ready"|"running"|"finished";dump:string[]}
type Action={type:"ready";scenario:Scenario;dump:string}|{type:"running";dump:string}|{type:"finished";result:Result;dump:string}|{type:"reset"}|{type:"error";dump:string}
const initial:State={scenario:null,result:null,phase:"catalog",dump:[]}
function reducer(state:State,action:Action):State{if(action.type==="reset")return initial;if(action.type==="ready")return{scenario:action.scenario,result:null,phase:"ready",dump:[...state.dump,action.dump]};if(action.type==="running")return{...state,phase:"running",dump:[...state.dump,action.dump]};if(action.type==="finished")return{...state,result:action.result,phase:"finished",dump:[...state.dump,action.dump]};return{...state,phase:"finished",dump:[...state.dump,action.dump]}}
const technical=(label:string,value:unknown)=>`[${new Date().toISOString()}] ${label}\n${JSON.stringify(value,null,2)}`

export function LabSandboxScreen({onEnter}:{onEnter:(screen:Screen)=>void}){
  const [cards,setCards]=useState<CatalogCard[]>([]);const [query,setQuery]=useState("");const [selected,setSelected]=useState<CatalogCard|null>(null);const [state,dispatch]=useReducer(reducer,initial);const [busy,setBusy]=useState(false);const [toast,setToast]=useState("")
  useEffect(()=>{void supabase.from("cards").select("id,code,name,image_url,element,rarity,card_type,base_power,base_max_life,effect_mana_cost,effect_text").eq("is_active",true).order("name").then(({data,error})=>{if(error)dispatch({type:"error",dump:technical("ERRO AO CARREGAR CATÁLOGO",error)});else setCards((data??[])as CatalogCard[])})},[])
  const filtered=useMemo(()=>{const term=query.trim().toLocaleLowerCase("pt-BR");return cards.filter(card=>!term||card.name.toLocaleLowerCase("pt-BR").includes(term)||card.code.toLowerCase().includes(term)).slice(0,100)},[cards,query])
  const cardView=(card:CatalogCard):GameCardType=>({id:card.id,nome:card.name,image_url:card.image_url,elemento:card.element,raridade:card.rarity,tipo:card.element,mana:card.effect_mana_cost,ataque:card.base_power,vida:card.base_max_life,efeito:card.effect_text??""})
  const captureError=(operation:string,error:unknown,payload:unknown)=>{const issue=error as {message?:string;details?:string;hint?:string;code?:string;stack?:string};const stack=error instanceof Error?error.stack:new Error(issue?.message??String(error)).stack;dispatch({type:"error",dump:technical(`${operation} · PAYLOAD`,payload)+"\n"+technical(`${operation} · ERRO HTTP/SQL`,{message:issue?.message,details:issue?.details,hint:issue?.hint,code:issue?.code,stack})})}
  const start=async()=>{if(!selected||busy)return;setBusy(true);dispatch({type:"reset"});const payload={p_card_id:selected.code};try{const {data,error}=await supabase.rpc("create_lab_unit_test",payload);if(error)throw error;const scenario=data as Scenario;if(!scenario?.test_id)throw new Error("LAB_SCENARIO_NOT_RETURNED");dispatch({type:"ready",scenario,dump:technical("RPC create_lab_unit_test · PAYLOAD",payload)+"\n"+technical("RPC create_lab_unit_test · RETORNO",scenario)})}catch(error){captureError("create_lab_unit_test",error,payload)}finally{setBusy(false)}}
  const execute=async()=>{if(!state.scenario||busy||state.phase!=="ready")return;setBusy(true);const payload={p_test_id:state.scenario.test_id,p_action:{type:state.scenario.action_type,source_card_id:state.scenario.card_id,target:"practice_dummy"}};dispatch({type:"running",dump:technical("RPC execute_lab_unit_test · PAYLOAD",payload)});try{const {data,error}=await supabase.rpc("execute_lab_unit_test",payload);if(error)throw error;const result=data as Result;dispatch({type:"finished",result,dump:technical("RPC execute_lab_unit_test · RETORNO",result)})}catch(error){captureError("execute_lab_unit_test",error,payload)}finally{setBusy(false)}}
  const dump=state.dump.join("\n\n"),copy=async()=>{await navigator.clipboard.writeText(dump);setToast("Log copiado! Cole no chat para depuração.");window.setTimeout(()=>setToast(""),2800)}
  const audited=selected&&cardView(selected),before=state.scenario?.before,after=state.result?.after
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#3b0764,#09090b_55%)] p-5 pt-20 text-stone-100"><div className="mx-auto max-w-[1700px]"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-serif text-3xl font-black text-purple-100"><Beaker className="mr-2 inline text-emerald-300"/>Laboratório Unitário Ofieri</h1><p className="text-sm text-purple-200">Engine determinística isolada · sem duelo, bot, turnos, banimento ou relógio.</p></div><button onClick={()=>onEnter("hub")} className="rounded border border-stone-500 bg-black/60 px-4 py-2 text-xs font-black"><X className="mr-1 inline" size={15}/>VOLTAR AO HUB</button></header>
  <section className="mt-5 rounded-xl border border-purple-500/40 bg-black/45 p-4"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-purple-300" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar por código ou nome: Guillaume, Gerd, Harpia…" className="w-full rounded-lg border border-purple-400/50 bg-stone-950 py-3 pl-10 pr-3 text-sm"/></div><div className="mt-3 flex gap-3 overflow-x-auto pb-2">{filtered.map(card=><button key={card.id} onClick={()=>{setSelected(card);dispatch({type:"reset"})}} className={`w-28 shrink-0 rounded-lg border p-2 text-left ${selected?.id===card.id?"border-emerald-300 bg-emerald-950/50":"border-purple-800 bg-black/40"}`}><b className="block text-[9px] text-amber-100">{card.name}</b><small className="text-[7px] text-stone-500">{card.code}</small></button>)}</div></section>
  <div className="mt-5 grid gap-5 xl:grid-cols-[320px_1fr_420px]"><section className="rounded-2xl border-2 border-amber-400/60 bg-black/70 p-5"><h2 className="mb-4 text-center font-serif text-sm font-black uppercase text-amber-200">A Carta Auditada</h2>{audited?<><div className="mx-auto aspect-[2/3] w-64"><GameCard card={audited} enableZoom/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span>⚔️ {audited.ataque}</span><span>❤️ {audited.vida}</span><span>⚡ {audited.mana}</span></div><p className="mt-3 rounded border border-amber-800 bg-amber-950/25 p-3 text-xs leading-relaxed text-amber-100"><b>EFEITO OFICIAL:</b> {audited.efeito||"Sem texto cadastrado."}</p><button disabled={busy} onClick={()=>void start()} className="mt-4 w-full rounded-xl border-2 border-emerald-200 bg-emerald-800 px-4 py-4 font-serif text-xs font-black uppercase disabled:opacity-40">{busy&&state.phase==="catalog"?<Loader2 className="mr-2 inline animate-spin"/>:null}🧪 INICIAR TESTE UNITÁRIO</button></>:<p className="py-52 text-center text-stone-500">Selecione uma carta.</p>}</section>
  <section className="rounded-2xl border border-purple-400/50 bg-black/60 p-6"><h2 className="text-center font-serif text-lg font-black uppercase text-purple-100">Mesa de Teste Cirúrgico</h2>{state.scenario?<><div className="mt-8 grid items-center gap-6 md:grid-cols-[1fr_auto_1fr]"><article className="rounded-xl border border-emerald-400 bg-emerald-950/30 p-4 text-center"><p className="text-xs font-black text-emerald-200">SUA CARTA · {before?.audited_card.zone}</p><div className="mx-auto mt-3 aspect-[2/3] w-44">{audited&&<GameCard card={{...audited,ataque:after?.audited_card.power??before?.audited_card.power??audited.ataque,vida:after?.audited_card.life??before?.audited_card.life??audited.vida}}/>}</div></article><b className="text-center font-serif text-3xl text-amber-300">VS</b><article className="rounded-xl border border-red-400 bg-red-950/30 p-4 text-center"><p className="text-xs font-black text-red-200">BONECO DE PRÁTICA</p><div className="mx-auto mt-3 flex aspect-[2/3] w-44 flex-col items-center justify-center rounded-xl border-4 border-slate-400 bg-gradient-to-b from-stone-700 to-black"><span className="text-6xl">🎯</span><b className="mt-5 text-red-100">⚔️ {after?.practice_dummy.power??before?.practice_dummy.power} · ❤️ {after?.practice_dummy.life??before?.practice_dummy.life}</b><small className="mt-2 text-stone-400">Comum · Defesa</small></div></article></div><button disabled={busy||state.phase!=="ready"} onClick={()=>void execute()} className="mx-auto mt-8 block rounded-xl border-2 border-yellow-200 bg-gradient-to-r from-amber-900 via-yellow-600 to-amber-900 px-8 py-4 font-serif text-sm font-black uppercase disabled:opacity-35">{busy?<Loader2 className="mr-2 inline animate-spin"/>:null}{state.scenario.action_type==="declare_attack"?"⚔️ DECLARAR ATAQUE ÚNICO":"✨ ATIVAR EFEITO ÚNICO"}</button></>:<p className="py-64 text-center text-stone-500">Inicie o teste para injetar o cenário estático.</p>}</section>
  <aside className="rounded-2xl border border-cyan-400/50 bg-stone-950/85 p-5"><h2 className="font-serif text-lg font-black text-cyan-100">Feed de Prova de Funcionamento</h2><div className="mt-4 space-y-3 text-xs"><p className={state.scenario?"text-emerald-200":"text-stone-500"}>{state.scenario?`✅ Cenário injetado: ${state.scenario.card_name} (${before?.audited_card.power} ATK) e Boneco de Prática (${before?.practice_dummy.life} HP / Comum).`:"1 · Aguardando seleção e injeção do cenário."}</p><p className={state.phase==="ready"?"animate-pulse text-amber-200":"text-stone-500"}>{state.phase==="ready"?`⏳ Aguardando ação do usuário: ${state.scenario?.action_type==="declare_attack"?"declare o ataque contra o Boneco de Prática.":"ative o efeito autorizado."}`:"2 · A ação única ainda não foi liberada."}</p><p className={state.result?.success?"text-purple-200":"text-stone-500"}>{state.result?`✨ ${state.result.message}`:"3 · O resultado SQL aparecerá aqui."}</p></div>{state.result&&<div className={`mt-5 rounded-xl border-2 p-4 text-center font-serif text-sm font-black ${state.result.approved?"border-emerald-300 bg-emerald-950 text-emerald-100":"border-red-400 bg-red-950 text-red-100"}`}>{state.result.approved?<CheckCircle2 className="mx-auto mb-2"/>:<XCircle className="mx-auto mb-2"/>}{state.result.approved?"[ ✅ TESTE APROVADO: EFEITO 100% OPERACIONAL ]":"[ ❌ TESTE FALHOU: DIVERGÊNCIA DE MECÂNICA ]"}</div>}<div className="mt-6 flex items-center justify-between gap-2"><h3 className="text-xs font-black uppercase text-red-200">Dump técnico</h3><button disabled={!dump} onClick={()=>void copy()} className="rounded border-2 border-cyan-300 bg-blue-900 px-3 py-2 text-[9px] font-black text-cyan-50 disabled:opacity-30"><Clipboard className="mr-1 inline" size={13}/>COPIAR LOG TÉCNICO PARA DEPURAÇÃO</button></div><textarea readOnly value={dump} className={`mt-2 h-72 w-full resize-none rounded-lg border bg-black p-3 font-mono text-[9px] leading-relaxed ${state.phase==="finished"&&!state.result?.success?"border-red-500 text-red-300":"border-stone-700 text-emerald-200"}`} placeholder="Payloads, respostas e stack traces serão capturados aqui."/>{toast&&<div className="mt-2 rounded bg-emerald-900 p-2 text-center text-xs text-emerald-100">{toast}</div>}</aside></div></div></main>
}
