"use client"

import { useEffect, useMemo, useReducer, useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { Beaker, BookOpen, CheckCircle2, Clipboard, Cog, Layers, Loader2, RotateCcw, Search, Shield, Skull, Sparkles, Swords, X, XCircle, Zap } from "lucide-react"
import { supabase } from "@/lib/supabase"
import type { Screen } from "@/lib/types"
import type { GameCard as GameCardType, OfficialCardType, Rarity } from "@/lib/game-data"
import { GameCard } from "@/components/game/game-card"

type CatalogCard={id:string;code:string;name:string;image_url:string|null;element:OfficialCardType;rarity:Rarity;card_type:string;base_power:number;base_max_life:number;effect_mana_cost:number;effect_text:string|null}
type BoardState={audited_card:{name:string;power:number;life:number;zone:string};practice_dummy:{name:string;power:number;life:number;rarity:string;zone:string};enemy_deck_count:number;player_hand_count:number;mana_available?:number;harpies_in_deck?:number}
type Scenario={test_id:string;card_id:string;card_name:string;effect_code:string;action_type:"activate_effect"|"declare_attack";objective:string;required_mana:number;before:BoardState;status:"ready"}
type Result={success:boolean;approved:boolean;status:string;effect_code:string;message:string;before:BoardState;after:BoardState;proof:Record<string,unknown>;reason?:string}
type State={scenario:Scenario|null;result:Result|null;phase:"catalog"|"ready"|"running"|"finished";dump:string[]}
type Action={type:"ready";scenario:Scenario;dump:string}|{type:"running";dump:string}|{type:"finished";result:Result;dump:string}|{type:"reset"}|{type:"error";dump:string}
const initial:State={scenario:null,result:null,phase:"catalog",dump:[]}
function reducer(state:State,action:Action):State{if(action.type==="reset")return initial;if(action.type==="ready")return{scenario:action.scenario,result:null,phase:"ready",dump:[action.dump]};if(action.type==="running")return{...state,phase:"running",dump:[...state.dump,action.dump]};if(action.type==="finished")return{...state,result:action.result,phase:"finished",dump:[...state.dump,action.dump]};return{...state,phase:"finished",dump:[...state.dump,action.dump]}}
const technical=(label:string,value:unknown)=>`[${new Date().toISOString()}] ${label}\n${JSON.stringify(value,null,2)}`
const dummyCard=(name:string,power:number,life:number,rarity:Rarity="common"):GameCardType=>({id:`lab-${name}`,nome:name,image_url:null,elemento:"Cívil",raridade:rarity,tipo:"Cívil",mana:0,ataque:power,vida:life,efeito:"Alvo materializado exclusivamente para a simulação tática."})

function EmptySlot({label,tone="amber"}:{label:string;tone?:"amber"|"red"|"blue"}){const color=tone==="red"?"border-red-500/35":tone==="blue"?"border-blue-400/35":"border-amber-400/30";return <div className={`flex aspect-[2/3] w-24 shrink-0 items-center justify-center rounded-[40%] border border-dashed ${color} bg-black/20 text-center font-serif text-[8px] uppercase text-stone-600`}>{label}</div>}
function Zone({title,children,slots=3,tone="amber"}:{title:string;children?:React.ReactNode;slots?:number;tone?:"amber"|"red"|"blue"}){const count=Array.isArray(children)?children.filter(Boolean).length:children?1:0;return <section><p className="mb-1 text-center font-serif text-[9px] font-black uppercase tracking-[.2em] text-amber-300">{title}</p><div className="flex min-h-36 items-center justify-center gap-3 rounded-xl border border-white/5 bg-black/20 px-3 py-2">{children}{Array.from({length:Math.max(0,slots-count)},(_,i)=><EmptySlot key={i} label={title} tone={tone}/>)}</div></section>}

export function LabSandboxScreen({onEnter}:{onEnter:(screen:Screen)=>void}){
  const [cards,setCards]=useState<CatalogCard[]>([]),[query,setQuery]=useState(""),[selected,setSelected]=useState<CatalogCard|null>(null),[drawer,setDrawer]=useState(true),[tab,setTab]=useState<"chronicle"|"technical">("chronicle"),[busy,setBusy]=useState(false),[toast,setToast]=useState("");const [state,dispatch]=useReducer(reducer,initial)
  useEffect(()=>{void supabase.from("cards").select("id,code,name,image_url,element,rarity,card_type,base_power,base_max_life,effect_mana_cost,effect_text").eq("is_active",true).order("name").then(({data,error})=>{if(error)dispatch({type:"error",dump:technical("ERRO AO CARREGAR CATÁLOGO",error)});else setCards((data??[])as CatalogCard[])})},[])
  const filtered=useMemo(()=>{const term=query.trim().toLocaleLowerCase("pt-BR");return cards.filter(card=>!term||card.name.toLocaleLowerCase("pt-BR").includes(term)||card.code.toLowerCase().includes(term)).slice(0,100)},[cards,query])
  const cardView=(card:CatalogCard):GameCardType=>({id:card.id,nome:card.name,image_url:card.image_url,elemento:card.element,raridade:card.rarity,tipo:card.element,mana:card.effect_mana_cost,ataque:card.base_power,vida:card.base_max_life,efeito:card.effect_text??""})
  const capture=(operation:string,error:unknown,payload:unknown)=>{const issue=error as {message?:string;details?:string;hint?:string;code?:string;stack?:string};dispatch({type:"error",dump:technical(`${operation} · PAYLOAD`,payload)+"\n"+technical(`${operation} · ERRO HTTP/SQL`,{message:issue?.message,details:issue?.details,hint:issue?.hint,code:issue?.code,stack:error instanceof Error?error.stack:new Error(issue?.message??String(error)).stack})})}
  const conjure=async(card=selected)=>{if(!card||busy)return;setBusy(true);setSelected(card);dispatch({type:"reset"});const payload={p_card_id:card.code};try{const {data,error}=await supabase.rpc("create_lab_unit_test",payload);if(error)throw error;const scenario=data as Scenario;if(!scenario?.test_id)throw new Error(JSON.stringify(data));dispatch({type:"ready",scenario,dump:technical("RPC create_lab_unit_test · PAYLOAD",payload)+"\n"+technical("RPC create_lab_unit_test · RETORNO",scenario)});setDrawer(false);setTab("chronicle")}catch(error){capture("create_lab_unit_test",error,payload)}finally{setBusy(false)}}
  const execute=async()=>{if(!state.scenario||busy||state.phase!=="ready")return;setBusy(true);const payload={p_test_id:state.scenario.test_id,p_action:{type:state.scenario.action_type,source_card_id:state.scenario.card_id,target:"practice_dummy"}};dispatch({type:"running",dump:technical("RPC execute_lab_unit_test · PAYLOAD",payload)});try{const {data,error}=await supabase.rpc("execute_lab_unit_test",payload);if(error)throw error;dispatch({type:"finished",result:data as Result,dump:technical("RPC execute_lab_unit_test · RETORNO",data)})}catch(error){capture("execute_lab_unit_test",error,payload)}finally{setBusy(false)}}
  const dump=state.dump.join("\n\n"),copy=async()=>{await navigator.clipboard.writeText(dump);setToast("Log copiado! Cole no chat para depuração.");window.setTimeout(()=>setToast(""),2600)}
  const audited=selected&&cardView(selected),board=state.result?.after??state.scenario?.before,isHarpy=state.scenario?.effect_code==="common_harpy_absorb_and_attack",isGerd=state.scenario?.effect_code==="common_gerd_double_life",targetDestroyed=Boolean(state.result&&(state.result.after.practice_dummy.life<=0||state.result.proof.destroyed))
  const chronicle=state.scenario?[`🔮 [Cenário Conjurado] As Areias de Ofier recriam o campo para testar ${state.scenario.card_name} (${state.scenario.before.audited_card.power} ATK). ${isGerd?"O passe anterior do Autômato foi selado no histórico.":isHarpy?"Dez Harpias aguardam ocultas no seu grimório e duas Cartas de Vida rivais vigiam o horizonte.":"O Autômato posicionou uma defesa comum de 1000 HP na linha de frente."}`,`🎯 DIRETRIZ DO TESTE: ${state.scenario.objective}`,...(state.phase==="running"?["⚔️ [Ação nas Areias] A carta avança enquanto o motor SQL calcula a resolução autoritativa…"]:[]),...(state.result?[state.result.approved?`✨ [Resolução Mágica] ${state.result.message} A simulação tática foi validada com perfeição.`:`❌ [Divergência Arcana] ${state.result.reason??state.result.message}`]:[])]:["Abra o Grimório de Simulação e escolha a carta que deseja auditar."]
  const restart=()=>{if(selected)void conjure(selected)},chooseAnother=()=>{dispatch({type:"reset"});setDrawer(true);setSelected(null)}
  return <main className="relative h-screen overflow-hidden bg-[url('/yang-69TcSUVhbmY-unsplash.jpg')] bg-cover bg-center text-stone-100"><div className="absolute inset-0 bg-gradient-to-b from-black/90 via-black/60 to-black/90 backdrop-blur-[2px]"/><div className="relative z-10 grid h-full grid-cols-[minmax(720px,1fr)_370px] gap-3 p-3 pt-16">
    <section className="flex min-h-0 flex-col overflow-y-auto rounded-2xl border border-amber-700/35 bg-black/25 p-3"><header className="mb-2 flex items-center justify-between rounded-xl border border-red-800/40 bg-stone-950/80 px-4 py-2"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-red-400 bg-red-950"><Shield/></div><div><p className="text-[9px] uppercase tracking-widest text-red-300">Oponente controlado</p><h1 className="font-serif text-sm font-black text-red-100">Autômato de Ofier (Simulação Tática)</h1></div></div><div className="rounded-full border border-purple-300 bg-purple-950 px-4 py-2 font-serif text-[10px] font-black text-purple-100">[ ⏳ SIMULAÇÃO TÁTICA: TURNO ÚNICO DE {state.scenario?.action_type==="declare_attack"?"ATAQUE":"CONJURAÇÃO"} ]</div><button onClick={()=>onEnter("hub")} className="rounded border border-stone-600 bg-black px-3 py-2 text-[9px] font-black"><X className="mr-1 inline" size={13}/>SAIR</button></header>
    <Zone title="Cartas de Vida do Autômato" slots={isHarpy?2:3} tone="red">{isHarpy&&[0,1].map(i=><motion.div key={i} layout className="aspect-[2/3] w-24"><GameCard card={dummyCard(`Sentinela de Vida ${i+1}`,700+i*100,1800,"rare")}/></motion.div>)}</Zone>
    <Zone title="Campo de Reforço do Autômato" slots={3} tone="blue">{state.scenario&&!isGerd&&!isHarpy&&<motion.div onDragOver={e=>e.preventDefault()} onDrop={()=>void execute()} animate={targetDestroyed?{opacity:0,scale:.15,rotate:35,filter:"blur(12px)"}:{opacity:1,scale:1}} transition={{duration:.8}} className="aspect-[2/3] w-24"><GameCard card={dummyCard("Boneco de Prática",board?.practice_dummy.power??500,board?.practice_dummy.life??1000)}/></motion.div>}</Zone>
    <Zone title="Campo de Ataque do Autômato" slots={3} tone="red"/>
    <div className="my-1 flex items-center justify-between border-y border-amber-600/50 bg-stone-950/95 px-5 py-2"><span className="flex items-center gap-2 text-xs text-red-200"><Skull size={15}/> Deck rival: {board?.enemy_deck_count??10}</span><b className="font-serif text-sm text-amber-100">AREIAS DE OFIER · UMA ÚNICA RESOLUÇÃO</b><span className="flex items-center gap-2 text-xs text-cyan-200"><Zap size={15}/> Mana exata: {state.scenario?.required_mana??0}</span></div>
    <Zone title="Seu Campo de Ataque" slots={3}>{audited&&state.scenario&&!isGerd&&<motion.div animate={state.phase==="running"?{y:[0,-28,-95,0],scale:[1,1.15,1.25,1]}:{y:0,scale:1}} transition={{duration:1.25}} className="aspect-[2/3] w-24"><div draggable onDragStart={event=>event.dataTransfer.setData("text/lab-card",audited.id)} className="h-full w-full cursor-grab"><GameCard card={{...audited,ataque:board?.audited_card.power??audited.ataque,vida:board?.audited_card.life??audited.vida}} enableZoom/></div></motion.div>}</Zone>
    <Zone title="Seu Campo de Reforço" slots={3} tone="blue"/>
    <Zone title="Suas Cartas de Vida" slots={3} tone="red">{audited&&state.scenario&&isGerd&&<motion.div animate={state.phase==="running"?{scale:[1,1.2,1],filter:["brightness(1)","brightness(2)","brightness(1)"]}:{scale:1}} className="aspect-[2/3] w-24"><GameCard card={{...audited,vida:board?.audited_card.life??audited.vida}} enableZoom/></motion.div>}</Zone>
    <div className="sticky bottom-0 mt-2 flex min-h-24 items-end justify-center rounded-t-[35px] border-x border-t border-amber-700/40 bg-black/75 p-3"><div className="absolute left-4 top-3 flex items-center gap-2 text-[10px] text-amber-200"><Layers size={15}/> Mão cirúrgica · somente recursos necessários</div>{!state.scenario&&<button onClick={()=>setDrawer(true)} className="rounded-xl border-2 border-purple-300 bg-purple-950 px-8 py-4 font-serif font-black text-purple-100"><BookOpen className="mr-2 inline"/>ABRIR GRIMÓRIO DE SIMULAÇÃO</button>}{state.scenario&&<button disabled={busy||state.phase!=="ready"} onClick={()=>void execute()} className="rounded-xl border-2 border-yellow-200 bg-gradient-to-r from-amber-950 via-yellow-600 to-amber-950 px-8 py-4 font-serif text-sm font-black uppercase text-white shadow-[0_0_28px_rgba(250,204,21,.45)] disabled:opacity-35">{busy?<Loader2 className="mr-2 inline animate-spin"/>:state.scenario.action_type==="declare_attack"?<Swords className="mr-2 inline"/>:<Sparkles className="mr-2 inline"/>}{state.scenario.action_type==="declare_attack"?"DECLARAR ATAQUE CONTRA O ALVO":"ATIVAR EFEITO NO PAINEL ARCANO"}</button>}</div></section>
    <aside className="flex min-h-0 flex-col rounded-2xl border border-amber-700/45 bg-stone-950/90 p-4"><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTab("chronicle")} className={`rounded-lg border px-2 py-3 text-[10px] font-black ${tab==="chronicle"?"border-amber-300 bg-amber-950 text-amber-100":"border-stone-700 text-stone-500"}`}><BookOpen className="mr-1 inline" size={14}/>📜 CRÔNICA DO GRIMÓRIO</button><button onClick={()=>setTab("technical")} className={`rounded-lg border px-2 py-3 text-[10px] font-black ${tab==="technical"?"border-cyan-300 bg-blue-950 text-cyan-100":"border-stone-700 text-stone-500"}`}><Cog className="mr-1 inline" size={14}/>⚙️ DIAGNÓSTICO TÉCNICO</button></div>{tab==="chronicle"?<div className="mt-4 flex-1 space-y-4 overflow-y-auto rounded-xl border border-amber-900/50 bg-[linear-gradient(135deg,rgba(69,26,3,.35),rgba(0,0,0,.65))] p-4 font-serif text-sm leading-relaxed">{chronicle.map((line,i)=><motion.p initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} key={`${i}-${line}`} className={line.startsWith("❌")?"text-red-200":line.startsWith("✨")?"text-purple-200":line.startsWith("🎯")?"font-black text-amber-200":"text-stone-200"}>{line}</motion.p>)}</div>:<div className="mt-4 flex min-h-0 flex-1 flex-col"><p className="mb-2 text-xs text-stone-400">Payloads RPC, retorno SQL, estado anterior/posterior e erros interceptados.</p><textarea readOnly value={dump} className="min-h-0 flex-1 resize-none rounded-xl border border-cyan-900 bg-black p-3 font-mono text-[9px] leading-relaxed text-emerald-200" placeholder="O dump técnico aparecerá após conjurar o cenário."/><button disabled={!dump} onClick={()=>void copy()} className="mt-3 rounded-xl border-2 border-cyan-300 bg-blue-900 px-3 py-4 text-[10px] font-black text-cyan-50 disabled:opacity-30"><Clipboard className="mr-2 inline"/>📋 COPIAR LOG TÉCNICO PARA DEPURAÇÃO</button>{toast&&<p className="mt-2 rounded bg-emerald-900 p-2 text-center text-xs text-emerald-100">{toast}</p>}</div>}</aside>
  </div>
  <AnimatePresence>{drawer&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[210] flex items-center justify-center bg-black/90 p-5 backdrop-blur-md"><motion.section initial={{y:60,scale:.94}} animate={{y:0,scale:1}} className="max-h-[92vh] w-full max-w-7xl overflow-y-auto rounded-2xl border-2 border-purple-300 bg-[radial-gradient(circle_at_top,#4c1d95,#09090b_65%)] p-6"><button onClick={()=>setDrawer(false)} className="float-right text-purple-200"><X/></button><h2 className="font-serif text-3xl font-black text-purple-100">📖 Grimório de Simulação Tática</h2><p className="mt-1 text-sm text-purple-200">Escolha uma carta para conjurar sua arena determinística de turno único.</p><div className="relative mt-5"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-purple-300"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por número, código ou nome…" className="w-full rounded-xl border border-purple-300/60 bg-black py-3 pl-11 pr-3"/></div><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8">{filtered.map(card=><button key={card.id} onClick={()=>setSelected(card)} className={`rounded-xl border-2 p-2 transition ${selected?.id===card.id?"border-emerald-300 bg-emerald-950/50 ring-2 ring-emerald-300":"border-purple-800 bg-black/40 hover:border-purple-300"}`}><div className="aspect-[2/3]"><GameCard card={cardView(card)}/></div><b className="mt-2 block text-[9px] text-amber-100">{card.code} · {card.name}</b></button>)}</div><button disabled={!selected||busy} onClick={()=>void conjure()} className="sticky bottom-2 mx-auto mt-6 block rounded-xl border-2 border-emerald-200 bg-gradient-to-r from-emerald-950 via-emerald-600 to-emerald-950 px-10 py-4 font-serif font-black uppercase text-white disabled:opacity-40"><Beaker className="mr-2 inline"/>🧪 CONJURAR SIMULAÇÃO TÁTICA</button></motion.section></motion.div>}</AnimatePresence>
  <AnimatePresence>{state.result&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[205] flex items-center justify-center bg-black/80 p-6 backdrop-blur-md"><motion.div initial={{scale:.65,y:40}} animate={{scale:1,y:0}} className={`w-full max-w-3xl rounded-2xl border-4 p-8 text-center shadow-2xl ${state.result.approved?"border-emerald-300 bg-[radial-gradient(circle,#14532d,#020617_70%)]":"border-red-400 bg-[radial-gradient(circle,#7f1d1d,#020617_70%)]"}`}>{state.result.approved?<CheckCircle2 className="mx-auto text-emerald-200" size={70}/>:<XCircle className="mx-auto text-red-200" size={70}/>}<h2 className="mt-4 font-serif text-3xl font-black uppercase text-white">{state.result.approved?"[ ✅ VALIDAÇÃO CONCLUÍDA: EFEITO 100% OPERACIONAL ]":"[ ❌ VALIDAÇÃO FALHOU: DIVERGÊNCIA DE MECÂNICA ]"}</h2><p className="mx-auto mt-4 max-w-xl text-sm text-stone-200">{state.result.message??state.result.reason}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={restart} className="rounded-xl border-2 border-cyan-300 bg-blue-900 px-5 py-4 font-black text-cyan-50"><RotateCcw className="mr-2 inline"/>🔄 REINICIAR ESTE CENÁRIO</button><button onClick={chooseAnother} className="rounded-xl border-2 border-purple-300 bg-purple-900 px-5 py-4 font-black text-purple-50"><Beaker className="mr-2 inline"/>🧪 ESCOLHER OUTRA CARTA</button></div></motion.div></motion.div>}</AnimatePresence>
  </main>
}
