"use client"

import { useEffect, useMemo, useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { Beaker, BookOpen, CheckCircle2, Clipboard, Cog, Layers, Loader2, RotateCcw, Search, Shield, Skull, Sparkles, Swords, X, XCircle, Zap } from "lucide-react"
import { supabase } from "@/lib/supabase"
import type { Screen } from "@/lib/types"
import type { GameCard as GameCardType, OfficialCardType, Rarity } from "@/lib/game-data"
import { GameCard } from "@/components/game/game-card"
import { useSandboxEngine } from "@/hooks/useSandboxEngine"
import { scenarioInstruction } from "@/lib/sandbox-scenario"
import { PreCombatModal } from "@/components/game/pre-combat-modal"
import { TriggerPromptModal } from "@/components/game/trigger-prompt-modal"
import type { PendingCardTrigger, VisibleMatchCard } from "@/lib/types"

type CatalogCard={id:string;code:string;name:string;image_url:string|null;element:OfficialCardType;rarity:Rarity;card_type:string;base_power:number;base_max_life:number;effect_mana_cost:number;effect_text:string|null}
const dummyCard=(name:string,power:number,life:number,rarity:Rarity="common"):GameCardType=>({id:`lab-${name}`,nome:name,image_url:null,elemento:"Cívil",raridade:rarity,tipo:"Cívil",mana:0,ataque:power,vida:life,efeito:"Alvo materializado exclusivamente para a simulação tática."})

function EmptySlot({label,tone="amber"}:{label:string;tone?:"amber"|"red"|"blue"}){const color=tone==="red"?"border-red-500/35":tone==="blue"?"border-blue-400/35":"border-amber-400/30";return <div className={`flex aspect-[2/3] w-24 shrink-0 items-center justify-center rounded-[40%] border border-dashed ${color} bg-black/20 text-center font-serif text-[8px] uppercase text-stone-600`}>{label}</div>}
function Zone({title,children,slots=3,tone="amber",onDrop}:{title:string;children?:React.ReactNode;slots?:number;tone?:"amber"|"red"|"blue";onDrop?:()=>void}){const count=Array.isArray(children)?children.filter(Boolean).length:children?1:0;return <section><p className="mb-1 text-center font-serif text-[9px] font-black uppercase tracking-[.2em] text-amber-300">{title}</p><div onDragOver={event=>{if(onDrop)event.preventDefault()}} onDrop={event=>{if(onDrop){event.preventDefault();onDrop()}}} className={`flex min-h-36 items-center justify-center gap-3 rounded-xl border bg-black/20 px-3 py-2 ${onDrop?"animate-pulse border-emerald-300 shadow-[inset_0_0_24px_rgba(52,211,153,.2)]":"border-white/5"}`}>{children}{Array.from({length:Math.max(0,slots-count)},(_,i)=><EmptySlot key={i} label={title} tone={tone}/>)}</div></section>}

export function LabSandboxScreen({onEnter}:{onEnter:(screen:Screen)=>void}){
  const [cards,setCards]=useState<CatalogCard[]>([]),[query,setQuery]=useState(""),[selected,setSelected]=useState<CatalogCard|null>(null),[drawer,setDrawer]=useState(true),[tab,setTab]=useState<"chronicle"|"technical">("chronicle"),[toast,setToast]=useState(""),[preCombatOpen,setPreCombatOpen]=useState(false);const state=useSandboxEngine();const busy=state.busy
  useEffect(()=>{void supabase.from("cards").select("id,code,name,image_url,element,rarity,card_type,base_power,base_max_life,effect_mana_cost,effect_text").eq("is_active",true).order("name").then(({data})=>setCards((data??[])as CatalogCard[]))},[])
  const filtered=useMemo(()=>{const term=query.trim().toLocaleLowerCase("pt-BR");return cards.filter(card=>!term||card.name.toLocaleLowerCase("pt-BR").includes(term)||card.code.toLowerCase().includes(term)).slice(0,100)},[cards,query])
  const cardView=(card:CatalogCard):GameCardType=>({id:card.id,nome:card.name,image_url:card.image_url,elemento:card.element,raridade:card.rarity,tipo:card.element,mana:card.effect_mana_cost,ataque:card.base_power,vida:card.base_max_life,efeito:card.effect_text??""})
  const conjure=async(card=selected)=>{if(!card)return;setSelected(card);if(await state.conjure(card.code)){setDrawer(false);setTab("chronicle")}}
  const copy=async()=>{await navigator.clipboard.writeText(state.dump);setToast("Log copiado! Cole no chat para depuração.");window.setTimeout(()=>setToast(""),2600)}
  const audited=selected&&cardView(selected),board=state.board,effectCode=state.scenario?.card.effect.effect_code,isHarpy=effectCode==="common_harpy_absorb_and_attack",isGerd=effectCode==="common_gerd_double_life",isReaction=state.scenario?.kind==="death_reaction",targetDestroyed=Boolean(state.result&&(state.result.after.practice_dummy?.life===0||state.result.proof.destroyed)),inMotion=["resolving","impact"].includes(state.phase)
  const labCard=audited&&state.scenario?{...audited,ataque:board?.audited_card.power??audited.ataque,vida:board?.audited_card.life??audited.vida,effect_definition:[state.scenario.card.effect]}:null
  const visibleLabCard=labCard&&state.scenario?{id:state.scenario.card.id,match_id:state.scenario.test_id,owner_user_id:"lab-user",zone:board?.audited_card.zone??"attacker",slot_index:0,is_face_up:true,current_power:board?.audited_card.power,current_life:board?.audited_card.life,max_life:board?.audited_card.max_life,card_data:labCard} as unknown as VisibleMatchCard:null
  const pendingTrigger=state.scenario&&isReaction?{id:`trigger-${state.scenario.test_id}`,match_id:state.scenario.test_id,owner_user_id:"lab-user",source_match_card_id:state.scenario.card.id,effect_order:state.scenario.card.effect.effect_order,effect_code:effectCode??"",trigger_type:state.scenario.card.effect.trigger_type,target_mode:state.scenario.card.effect.target_mode,mana_cost:state.scenario.card.mana_cost,description:state.scenario.card.effect_text,card_name:state.scenario.card.name,image_url:state.scenario.card.image_url,element:state.scenario.card.element,power:state.scenario.card.power,life:state.scenario.card.max_life,expected_state_version:0} as PendingCardTrigger:null
  const chronicle=state.scenario?[`🔮 [Cenário Conjurado] As Areias recriam o campo para auditar ${state.scenario.card.name} (Custo: ${state.scenario.card.mana_cost} | ATK: ${state.scenario.before.audited_card.power} | HP: ${state.scenario.before.audited_card.life}).`,`📐 [Alinhamento Tático] ${isGerd?"O Autômato passou a vez no turno anterior; Gerd ocupa o Campo de Vida.":isHarpy?"Dez Harpias ocultas aguardam no deck e duas Cartas de Vida protegem o Autômato.":isReaction?"O Autômato prepara um golpe letal para abrir a corrente de reação.":`O alvo favorável possui ${state.scenario.before.practice_dummy?.life??0} HP e o deck rival contém ${state.scenario.before.enemy_deck.length} cartas.`}`,`🎯 DIRETRIZ DO GRIMÓRIO: ${scenarioInstruction(state.scenario)}`,"⏳ [Aguardando Conjuração] O controle está em suas mãos. Execute a diretriz tática na mesa de combate.",...(inMotion?[`⚔️ [Ação] Foli aciona a mecânica de ${state.scenario.card.name} na mesa!`]:[]),...(state.result?[`💥 [Impacto Visual] O estado autoritativo alterou HP, ATK, mana, deck ou cemitério conforme a prova SQL.`,state.result.approved?`✨ [Consequência Mágica] ${state.result.message}`:`❌ [Divergência Arcana] ${state.result.reason??state.result.message}`]:[])]:["Abra o Grimório de Simulação e escolha a carta que deseja auditar."]
  const restart=()=>{if(selected)void conjure(selected)},chooseAnother=()=>{state.reset();setDrawer(true);setSelected(null)}
  return <motion.main animate={state.phase==="impact"?{x:[0,-8,7,-5,3,0],y:[0,4,-3,2,0]}:{x:0,y:0}} className="relative h-screen overflow-hidden bg-[url('/yang-69TcSUVhbmY-unsplash.jpg')] bg-cover bg-center text-stone-100"><div className="absolute inset-0 bg-gradient-to-b from-black/90 via-black/60 to-black/90 backdrop-blur-[2px]"/><div className="relative z-10 grid h-full grid-cols-[minmax(720px,1fr)_370px] gap-3 p-3 pt-16">
    <section className="flex min-h-0 flex-col overflow-y-auto rounded-2xl border border-amber-700/35 bg-black/25 p-3"><header className="mb-2 flex items-center justify-between rounded-xl border border-red-800/40 bg-stone-950/80 px-4 py-2"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-red-400 bg-red-950"><Shield/></div><div><p className="text-[9px] uppercase tracking-widest text-red-300">Oponente controlado</p><h1 className="font-serif text-sm font-black text-red-100">Autômato de Ofier (Simulação Tática)</h1></div></div><div className="max-w-lg animate-pulse rounded-lg border-2 border-purple-300 bg-purple-950 px-4 py-2 text-center font-serif text-[10px] font-black text-yellow-100">{state.scenario?`[ 🎯 DIRETRIZ DO GRIMÓRIO: ${scenarioInstruction(state.scenario)} ]`:"[ ⏳ AGUARDANDO ESCOLHA NO GRIMÓRIO ]"}</div><button onClick={()=>onEnter("hub")} className="rounded border border-stone-600 bg-black px-3 py-2 text-[9px] font-black"><X className="mr-1 inline" size={13}/>SAIR</button></header>
    <Zone title="Cartas de Vida do Autômato" slots={state.scenario&&!isGerd?2:3} tone="red">{state.scenario&&!isGerd&&board?.enemy_life.map(unit=><motion.div key={unit.id} layout className="aspect-[2/3] w-24"><GameCard card={dummyCard(unit.name,unit.power,unit.life,unit.rarity as Rarity)}/></motion.div>)}</Zone>
    <Zone title="Campo de Reforço do Autômato" slots={3} tone="blue">{state.scenario&&board?.practice_dummy&&!isHarpy&&<motion.div onDragOver={e=>e.preventDefault()} onDrop={()=>void state.execute()} animate={targetDestroyed?{opacity:0,scale:.15,rotate:35,filter:"blur(12px)"}:{opacity:1,scale:1}} transition={{duration:.8}} className="aspect-[2/3] w-24"><GameCard card={dummyCard(board.practice_dummy.name,board.practice_dummy.power,board.practice_dummy.life)}/></motion.div>}</Zone>
    <Zone title="Campo de Ataque do Autômato" slots={3} tone="red"/>
    <div className="my-1 flex items-center justify-between border-y border-amber-600/50 bg-stone-950/95 px-5 py-2"><span className="flex items-center gap-2 text-xs text-red-200"><Skull size={15}/> Deck rival: {board?.enemy_deck.length??0} · Cemitério: {board?.enemy_graveyard.length??0}</span><b className="font-serif text-sm text-amber-100">AREIAS DE OFIER · TURNO ÚNICO SIE</b><span className="flex items-center gap-2 text-xs text-cyan-200"><Zap size={15}/> Mana: {board?.mana_available??0}/{state.scenario?.card.mana_cost??0} · Deck aliado: {board?.player_deck.length??0}</span></div>
    <Zone title="Seu Campo de Ataque" slots={3}>{labCard&&state.scenario&&!isGerd&&board?.audited_card.zone==="attacker"&&<motion.div animate={inMotion?{y:[0,-28,-95,0],scale:[1,1.15,1.25,1]}:{y:0,scale:1}} transition={{duration:1.25}} className="aspect-[2/3] w-24"><div draggable={state.phase==="waiting"} onDragStart={event=>event.dataTransfer.setData("text/lab-card",labCard.id)} className="h-full w-full cursor-grab"><GameCard card={labCard} enableZoom/></div></motion.div>}</Zone>
    <Zone title="Seu Campo de Reforço" slots={3} tone="blue"/>
    <Zone title="Suas Cartas de Vida" slots={3} tone="red">{labCard&&state.scenario&&isGerd&&<motion.div animate={inMotion?{scale:[1,1.2,1],filter:["brightness(1)","brightness(2)","brightness(1)"]}:{scale:1}} className="aspect-[2/3] w-24"><GameCard card={labCard} enableZoom/></motion.div>}</Zone>
    <div className="sticky bottom-0 mt-2 flex min-h-24 items-end justify-center rounded-t-[35px] border-x border-t border-amber-700/40 bg-black/75 p-3"><div className="absolute left-4 top-3 flex items-center gap-2 text-[10px] text-amber-200"><Layers size={15}/> Sanctum unitário · aguardando comando manual</div>{!state.scenario&&<button onClick={()=>setDrawer(true)} className="rounded-xl border-2 border-purple-300 bg-purple-950 px-8 py-4 font-serif font-black text-purple-100"><BookOpen className="mr-2 inline"/>ABRIR GRIMÓRIO DE SIMULAÇÃO</button>}{state.scenario&&!isReaction&&<button disabled={busy||state.phase!=="waiting"} onClick={()=>state.scenario?.action_type==="activate_effect"?setPreCombatOpen(true):void state.execute()} className="rounded-xl border-2 border-yellow-200 bg-gradient-to-r from-amber-950 via-yellow-600 to-amber-950 px-8 py-4 font-serif text-sm font-black uppercase text-white shadow-[0_0_28px_rgba(250,204,21,.45)] disabled:opacity-35">{busy?<Loader2 className="mr-2 inline animate-spin"/>:state.scenario.action_type==="declare_attack"?<Swords className="mr-2 inline"/>:<Sparkles className="mr-2 inline"/>}{state.scenario.action_type==="declare_attack"?"DECLARAR ATAQUE CONTRA O ALVO":"ENCERRAR TURNO / CONJURAÇÕES"}</button>}</div></section>
    <aside className="flex min-h-0 flex-col rounded-2xl border border-amber-700/45 bg-stone-950/90 p-4"><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTab("chronicle")} className={`rounded-lg border px-2 py-3 text-[10px] font-black ${tab==="chronicle"?"border-amber-300 bg-amber-950 text-amber-100":"border-stone-700 text-stone-500"}`}><BookOpen className="mr-1 inline" size={14}/>📜 CRÔNICA DO GRIMÓRIO</button><button onClick={()=>setTab("technical")} className={`rounded-lg border px-2 py-3 text-[10px] font-black ${tab==="technical"?"border-cyan-300 bg-blue-950 text-cyan-100":"border-stone-700 text-stone-500"}`}><Cog className="mr-1 inline" size={14}/>⚙️ DUMP TÉCNICO & SQL</button></div>{tab==="chronicle"?<div className="mt-4 flex-1 space-y-4 overflow-y-auto rounded-xl border border-amber-900/50 bg-[linear-gradient(135deg,rgba(69,26,3,.35),rgba(0,0,0,.65))] p-4 font-serif text-sm leading-relaxed">{chronicle.map((line,i)=><motion.p initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} key={`${i}-${line}`} className={line.startsWith("❌")?"text-red-200":line.startsWith("✨")?"text-purple-200":line.startsWith("🎯")?"font-black text-amber-200":"text-stone-200"}>{line}</motion.p>)}</div>:<div className="mt-4 flex min-h-0 flex-1 flex-col"><p className="mb-2 text-xs text-stone-400">Payloads RPC, retorno SQL, estado anterior/posterior e erros interceptados.</p><textarea readOnly value={state.dump} className="min-h-0 flex-1 resize-none rounded-xl border border-cyan-900 bg-black p-3 font-mono text-[9px] leading-relaxed text-emerald-200" placeholder="O dump técnico aparecerá após conjurar o cenário."/><button disabled={!state.dump} onClick={()=>void copy()} className="mt-3 rounded-xl border-2 border-cyan-300 bg-blue-900 px-3 py-4 text-[10px] font-black text-cyan-50 disabled:opacity-30"><Clipboard className="mr-2 inline"/>📋 COPIAR LOG TÉCNICO PARA DEPURAÇÃO</button>{toast&&<p className="mt-2 rounded bg-emerald-900 p-2 text-center text-xs text-emerald-100">{toast}</p>}</div>}</aside>
  </div>
  <AnimatePresence>{state.phase==="impact"&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="pointer-events-none fixed inset-0 z-[202] flex items-center justify-center bg-black/65 backdrop-blur-sm"><motion.div initial={{scale:.45,rotate:-8}} animate={{scale:1,rotate:0}} className="rounded-2xl border-4 border-yellow-200 bg-[radial-gradient(circle,#581c87,#09090b_72%)] px-14 py-10 text-center shadow-[0_0_90px_rgba(250,204,21,.65)]"><Sparkles className="mx-auto text-yellow-200" size={64}/><h2 className="mt-4 font-serif text-4xl font-black uppercase text-yellow-100">✨ {isGerd?"GERD CONJURADO!":"EFEITO CONJURADO!"}</h2>{effectCode==="common_guillaume_destroy_deck"&&<p className="mt-3 text-lg font-black text-red-200">🔥 {String((state.result?.proof.revealed_card as {name?:string})?.name??"Carta rival")} foi revelada e desintegrada do deck para o cemitério.</p>}{isHarpy&&<p className="mt-3 text-lg font-black text-cyan-100">🪽 10 feixes deixam o deck · ATK 200 → 2200 · alvo: Sentinela Distante</p>}{isGerd&&<p className="mt-3 text-lg font-black text-red-100">❤️ HP 2000 → 4000 · Mana 2 → 0</p>}<p className="mt-3 max-w-xl text-sm font-black uppercase text-purple-200">HTTP {state.result?.http_status??200} confirmado. O tabuleiro já reflete a consequência SQL.</p></motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{drawer&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[210] flex items-center justify-center bg-black/90 p-5 backdrop-blur-md"><motion.section initial={{y:60,scale:.94}} animate={{y:0,scale:1}} className="max-h-[92vh] w-full max-w-7xl overflow-y-auto rounded-2xl border-2 border-purple-300 bg-[radial-gradient(circle_at_top,#4c1d95,#09090b_65%)] p-6"><button onClick={()=>setDrawer(false)} className="float-right text-purple-200"><X/></button><h2 className="font-serif text-3xl font-black text-purple-100">📖 Grimório de Simulação Tática</h2><p className="mt-1 text-sm text-purple-200">Escolha uma carta para conjurar sua arena determinística de turno único.</p><div className="relative mt-5"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-purple-300"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por número, código ou nome…" className="w-full rounded-xl border border-purple-300/60 bg-black py-3 pl-11 pr-3"/></div><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8">{filtered.map(card=><button key={card.id} onClick={()=>setSelected(card)} className={`rounded-xl border-2 p-2 transition ${selected?.id===card.id?"border-emerald-300 bg-emerald-950/50 ring-2 ring-emerald-300":"border-purple-800 bg-black/40 hover:border-purple-300"}`}><div className="aspect-[2/3]"><GameCard card={cardView(card)}/></div><b className="mt-2 block text-[9px] text-amber-100">{card.code} · {card.name}</b></button>)}</div><button disabled={!selected||busy} onClick={()=>void conjure()} className="sticky bottom-2 mx-auto mt-6 block rounded-xl border-2 border-emerald-200 bg-gradient-to-r from-emerald-950 via-emerald-600 to-emerald-950 px-10 py-4 font-serif font-black uppercase text-white disabled:opacity-40"><Beaker className="mr-2 inline"/>🧪 CONJURAR SIMULAÇÃO TÁTICA</button></motion.section></motion.div>}</AnimatePresence>
  <AnimatePresence>{preCombatOpen&&visibleLabCard&&<PreCombatModal cards={[visibleLabCard]} mana={board?.mana_available??0} busy={busy} freeUsed={false} paidUsed={false} onClose={()=>setPreCombatOpen(false)} onConfirm={staged=>{if(!staged.length)return;setPreCombatOpen(false);void state.execute()}}/>}</AnimatePresence>
  <AnimatePresence>{state.phase==="waiting"&&pendingTrigger&&visibleLabCard&&<TriggerPromptModal trigger={pendingTrigger} card={visibleLabCard} mana={board?.mana_available??0} busy={busy} onAccept={()=>void state.execute(true)} onDecline={()=>void state.execute(false)}/>}</AnimatePresence>
  <AnimatePresence>{state.phase==="finished"&&state.result&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[205] flex items-center justify-center bg-black/80 p-6 backdrop-blur-md"><motion.div initial={{scale:.65,y:40}} animate={{scale:1,y:0}} className={`w-full max-w-3xl rounded-2xl border-4 p-8 text-center shadow-2xl ${state.result.approved?"border-emerald-300 bg-[radial-gradient(circle,#14532d,#020617_70%)]":"border-red-400 bg-[radial-gradient(circle,#7f1d1d,#020617_70%)]"}`}>{state.result.approved?<CheckCircle2 className="mx-auto text-emerald-200" size={70}/>:<XCircle className="mx-auto text-red-200" size={70}/>}<h2 className="mt-4 font-serif text-3xl font-black uppercase text-white">{state.result.approved?"[ ✅ TESTE APROVADO: EFEITO 100% OPERACIONAL NA MESA ]":"[ ❌ VALIDAÇÃO FALHOU: DIVERGÊNCIA DE MECÂNICA ]"}</h2><p className="mx-auto mt-4 max-w-xl text-sm text-stone-200">{state.result.message??state.result.reason}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={restart} className="rounded-xl border-2 border-cyan-300 bg-blue-900 px-5 py-4 font-black text-cyan-50"><RotateCcw className="mr-2 inline"/>🔄 REINICIAR TESTE</button><button onClick={chooseAnother} className="rounded-xl border-2 border-purple-300 bg-purple-900 px-5 py-4 font-black text-purple-50"><Beaker className="mr-2 inline"/>🧪 TESTAR OUTRA CARTA</button></div></motion.div></motion.div>}</AnimatePresence>
  </motion.main>
}
