"use client"

import { useCallback, useReducer, useState } from "react"
import { supabase } from "@/lib/supabase"

export type SandboxBoard={audited_card:{name:string;power:number;life:number;zone:string};practice_dummy:{name:string;power:number;life:number;rarity:string;zone:string};enemy_deck_count:number;player_hand_count:number;mana_available?:number;harpies_in_deck?:number}
export type SandboxScenario={test_id:string;card_id:string;card_name:string;effect_code:string;action_type:"activate_effect"|"declare_attack";interaction_phase?:"WAITING_CARD_PLACEMENT"|"WAITING_USER_INPUT";objective:string;required_mana:number;before:SandboxBoard;status:string}
export type SandboxResult={success:boolean;approved:boolean;status:string;effect_code:string;message:string;before:SandboxBoard;after:SandboxBoard;proof:Record<string,unknown>;reason?:string;http_status?:number;state_mutated?:boolean}
type Phase="catalog"|"placing"|"waiting"|"resolving"|"impact"|"finished"
type State={scenario:SandboxScenario|null;result:SandboxResult|null;board:SandboxBoard|null;phase:Phase;dump:string[];events:string[]}
type Event={type:"reset"}|{type:"scenario";scenario:SandboxScenario;dump:string}|{type:"placed";board:SandboxBoard;dump:string}|{type:"resolving";dump:string}|{type:"impact";result:SandboxResult;dump:string}|{type:"finished"}|{type:"error";dump:string;message:string}
const initial:State={scenario:null,result:null,board:null,phase:"catalog",dump:[],events:[]}
const log=(label:string,value:unknown)=>`[${new Date().toISOString()}] ${label}\n${JSON.stringify(value,null,2)}`
function reducer(state:State,event:Event):State{switch(event.type){case"reset":return initial;case"scenario":return{scenario:event.scenario,result:null,board:event.scenario.before,phase:event.scenario.interaction_phase==="WAITING_CARD_PLACEMENT"?"placing":"waiting",dump:[event.dump],events:["scenario"]};case"placed":return{...state,board:event.board,phase:"waiting",dump:[...state.dump,event.dump],events:[...state.events,"placed"]};case"resolving":return{...state,phase:"resolving",dump:[...state.dump,event.dump],events:[...state.events,"command"]};case"impact":return{...state,result:event.result,board:event.result.after??state.board,phase:"impact",dump:[...state.dump,event.dump],events:[...state.events,"impact"]};case"finished":return{...state,phase:"finished",events:[...state.events,"finished"]};case"error":return{...state,phase:"finished",dump:[...state.dump,event.dump],events:[...state.events,event.message]}}}
const wait=(ms:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms))

export function useSandboxEngine(){
  const [state,dispatch]=useReducer(reducer,initial);const [busy,setBusy]=useState(false)
  const failure=useCallback((operation:string,error:unknown,payload:unknown)=>{const issue=error as {message?:string;details?:string;hint?:string;code?:string};const stack=error instanceof Error?error.stack:new Error(issue?.message??String(error)).stack;dispatch({type:"error",message:issue?.message??"Falha SQL",dump:log(`${operation} · PAYLOAD`,payload)+"\n"+log(`${operation} · ERRO HTTP/SQL`,{...issue,stack})})},[])
  const conjure=useCallback(async(cardCode:string)=>{if(busy)return false;setBusy(true);dispatch({type:"reset"});const payload={p_card_id:cardCode};try{const{data,error}=await supabase.rpc("create_lab_unit_test",payload);if(error)throw error;const scenario=data as SandboxScenario;if(!scenario?.test_id)throw new Error(JSON.stringify(data));dispatch({type:"scenario",scenario,dump:log("RPC create_lab_unit_test · PAYLOAD",payload)+"\n"+log("RPC create_lab_unit_test · RETORNO",scenario)});return true}catch(error){failure("create_lab_unit_test",error,payload);return false}finally{setBusy(false)}},[busy,failure])
  const placeCard=useCallback(async()=>{if(!state.scenario||state.phase!=="placing"||busy)return;setBusy(true);const payload={p_test_id:state.scenario.test_id,p_target_zone:"attacker"};try{const{data,error}=await supabase.rpc("play_lab_unit_test_card",payload);if(error)throw error;const result=data as {success:boolean;reason?:string;state:SandboxBoard};if(!result.success)throw new Error(result.reason??"LAB_CARD_PLACEMENT_FAILED");dispatch({type:"placed",board:result.state,dump:log("RPC play_lab_unit_test_card · PAYLOAD",payload)+"\n"+log("RPC play_lab_unit_test_card · RETORNO",result)})}catch(error){failure("play_lab_unit_test_card",error,payload)}finally{setBusy(false)}},[busy,failure,state.phase,state.scenario])
  const execute=useCallback(async()=>{if(!state.scenario||state.phase!=="waiting"||busy)return;setBusy(true);const rpc=state.scenario.action_type==="declare_attack"?"lab_declare_attack":"lab_activate_card_effect";const payload={p_test_id:state.scenario.test_id,p_action:{source_card_id:state.scenario.card_id,target:"practice_dummy",manual_user_input:true}};dispatch({type:"resolving",dump:log(`RPC ${rpc} · PAYLOAD`,payload)});try{const{data,error}=await supabase.rpc(rpc,payload);if(error)throw error;const result=data as SandboxResult;if(!result.success)throw new Error(result.reason??"LAB_ACTION_FAILED");dispatch({type:"impact",result,dump:log(`RPC ${rpc} · RETORNO HTTP ${result.http_status??200}`,result)});await wait(2500);dispatch({type:"finished"})}catch(error){failure(rpc,error,payload)}finally{setBusy(false)}},[busy,failure,state.phase,state.scenario])
  return{...state,busy,dump:state.dump.join("\n\n"),conjure,placeCard,execute,reset:()=>dispatch({type:"reset"})}
}
