"use client"

import { useCallback, useEffect, useState } from "react"
import { Check, UserPlus, Users, X } from "lucide-react"
import { supabase } from "@/lib/supabase"
import { secureImageUrl } from "@/lib/secure-url"

type Contact = { request_id?: string; user_id: string; username: string; avatar_url: string | null; status: string; direction: "friend" | "received" | "sent" }

export function FriendsScreen() {
  const [contacts, setContacts] = useState<Contact[]>([]), [username, setUsername] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false)
  const load = useCallback(async () => { const { data, error } = await supabase.rpc("get_my_social_connections"); if (error) setMessage(readError(error)); else setContacts(Array.isArray(data) ? data : []) }, [])
  useEffect(() => { void load() }, [load])
  const send = async () => { if (!username.trim()) return; setBusy(true); setMessage(""); const { error } = await supabase.rpc("send_friend_request", { p_username: username.trim() }); setBusy(false); if (error) setMessage(readError(error)); else { setUsername(""); setMessage("Convite enviado."); void load() } }
  const respond = async (id: string, accept: boolean) => { setBusy(true); const { error } = await supabase.rpc("respond_friend_request", { p_request_id: id, p_accept: accept }); setBusy(false); if (error) setMessage(readError(error)); else void load() }
  return <main className="min-h-screen bg-stone-950 p-6 pt-20 text-stone-100"><div className="mx-auto max-w-5xl"><h1 className="font-serif text-3xl font-black text-amber-200"><Users className="mr-3 inline" />Contatos & Convites</h1><div className="my-6 flex gap-2 rounded-xl border border-amber-800/40 bg-black/50 p-4"><input value={username} onChange={e => setUsername(e.target.value)} placeholder="Nome exato do jogador" className="min-w-0 flex-1 rounded border border-stone-700 bg-stone-950 px-3 py-2" /><button disabled={busy} onClick={() => void send()} className="rounded border border-emerald-500 bg-emerald-950 px-4 font-bold"><UserPlus className="mr-2 inline" size={16} />CONVIDAR</button></div>{message && <p className="mb-4 rounded border border-amber-700/40 bg-amber-950/40 p-3 text-sm text-amber-100">{message}</p>}<div className="grid gap-3 md:grid-cols-2">{contacts.map(contact => <article key={`${contact.direction}-${contact.user_id}`} className="flex items-center gap-3 rounded-lg border border-stone-700 bg-black/50 p-4">{contact.avatar_url ? <img src={secureImageUrl(contact.avatar_url)} alt="" className="h-12 w-12 rounded-full object-cover" /> : <div className="h-12 w-12 rounded-full bg-amber-900" />}<div className="min-w-0 flex-1"><b className="block truncate text-amber-100">{contact.username}</b><span className="text-xs text-stone-400">{contact.direction === "friend" ? "Amigo" : contact.direction === "received" ? "Convite recebido" : "Convite enviado"}</span></div>{contact.direction === "received" && contact.request_id && <div className="flex gap-1"><button aria-label="Aceitar" disabled={busy} onClick={() => void respond(contact.request_id!, true)} className="rounded bg-emerald-800 p-2"><Check size={16} /></button><button aria-label="Recusar" disabled={busy} onClick={() => void respond(contact.request_id!, false)} className="rounded bg-red-900 p-2"><X size={16} /></button></div>}</article>)}</div>{!contacts.length && !message && <p className="py-16 text-center text-stone-500">Nenhum contato ou convite.</p>}</div></main>
}
function readError(error: { message: string; details?: string; hint?: string; code?: string }) { return [error.message, error.details, error.hint, error.code && `Código: ${error.code}`].filter(Boolean).join(" · ") }
