"use client"

import { useCallback, useEffect, useState } from "react"
import { ScrollText } from "lucide-react"
import { supabase } from "@/lib/supabase"

type Note = { id: string; version: string; title: string; body: string; published_at: string }
export function PatchNotesScreen() {
  const [notes, setNotes] = useState<Note[]>([]), [isAdmin, setIsAdmin] = useState(false), [version, setVersion] = useState(""), [title, setTitle] = useState(""), [body, setBody] = useState(""), [message, setMessage] = useState("")
  const load = useCallback(async () => { const [{ data, error }, { data: user }] = await Promise.all([supabase.from("patch_notes").select("id,version,title,body,published_at").eq("is_published", true).order("published_at", { ascending: false }), supabase.auth.getUser()]); if (error) setMessage(error.message); else setNotes(data ?? []); if (user.user) { const role = await supabase.from("user_roles").select("role").eq("user_id", user.user.id).in("role", ["content_editor", "game_master", "admin"]).limit(1).maybeSingle(); setIsAdmin(Boolean(role.data)) } }, [])
  useEffect(() => { void load() }, [load])
  const publish = async () => { setMessage(""); const { error } = await supabase.rpc("publish_patch_note", { p_version: version.trim(), p_title: title.trim(), p_body: body.trim() }); if (error) setMessage(error.message); else { setVersion(""); setTitle(""); setBody(""); setMessage("Atualização publicada."); void load() } }
  return <main className="min-h-screen bg-stone-950 p-6 pt-20 text-stone-100"><div className="mx-auto max-w-4xl"><h1 className="font-serif text-3xl font-black text-amber-200"><ScrollText className="mr-3 inline" />Notas de Atualização</h1>{isAdmin && <section className="my-6 grid gap-3 rounded-xl border border-amber-600/50 bg-black/60 p-5"><h2 className="font-serif text-xl text-amber-100">Publicar atualização semanal</h2><div className="grid gap-3 sm:grid-cols-2"><input value={version} onChange={e => setVersion(e.target.value)} placeholder="Versão (ex.: ofieri-1.1)" className="rounded border border-stone-700 bg-stone-950 p-2" /><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Título" className="rounded border border-stone-700 bg-stone-950 p-2" /></div><textarea value={body} onChange={e => setBody(e.target.value)} placeholder="Conteúdo da atualização" rows={7} className="rounded border border-stone-700 bg-stone-950 p-3" /><button disabled={!version.trim() || !title.trim() || !body.trim()} onClick={() => void publish()} className="justify-self-start rounded border border-amber-500 bg-amber-900 px-5 py-2 font-bold disabled:opacity-40">PUBLICAR</button></section>}{message && <p className="my-4 rounded border border-amber-700/40 bg-amber-950/40 p-3">{message}</p>}<div className="space-y-4">{notes.map(note => <article key={note.id} className="rounded-xl border border-amber-800/40 bg-black/50 p-6"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-serif text-2xl font-bold text-amber-100">{note.title}</h2><span className="text-xs text-amber-500">{note.version} · {new Date(note.published_at).toLocaleDateString("pt-BR")}</span></div><p className="mt-4 whitespace-pre-wrap leading-relaxed text-stone-300">{note.body}</p></article>)}</div>{!notes.length && !message && <p className="py-16 text-center text-stone-500">Nenhuma atualização publicada.</p>}</div></main>
}
