-- Catálogo comum transcrito do Discord. Valores 0/? foram normalizados para 1 por decisão editorial.
insert into public.card_sets(code,name,description,is_collab,is_active,release_date)
values('OFIERI_COMMON','Ofieri — Cartas Comuns','Primeiro catálogo comum autoritativo',false,true,current_date)
on conflict(code) do update set name=excluded.name,description=excluded.description,is_active=true,updated_at=now();

with source(n,name,life,power,mana,effect_text) as (values
(0,'Filho da Puta Junior',1,0,0,'Você não pode comprar cartas enquanto esta carta estiver na sua mão.'),
(1,'Dijkistra',2100,1600,0,'Se descartada por um efeito, compre 3 cartas comuns do seu deck.'),
(2,'Duny',720,1600,0,'Impede que cartas destruídas no campo retornem à mão ou ao campo.'),
(3,'Javali',500,3600,0,'Só ataca com uma mão não vazia composta apenas por comuns; seu ataque não revela nem permite reação do reforço atingido.'),
(4,'Erinia',1300,600,0,'Roube a carta de menor raridade da mão adversária e descarte uma carta da sua mão.'),
(5,'Endriuga',600,600,2,'Cause 500 de dano multiplicado pela quantidade de reforços inimigos a uma Carta de Vida escolhida.'),
(6,'Rei Henselt',2500,2500,7,'Ataque as 3 Cartas de Vida do oponente se ele não possuir reforços.'),
(7,'Aparição Diurna',1950,1950,2,'Ataque uma Carta de Vida inimiga aleatória se seu cemitério tiver mais de 4 cartas.'),
(8,'Aparição Noturna',1000,1500,1,'Se destruída como reforço, bloqueie o efeito de uma carta aleatória da mão inimiga.'),
(9,'Keira Metz',2500,1200,3,'Se destruída como Carta de Vida, substitua-a automaticamente por uma comum do deck.'),
(10,'Carniçal',2500,800,2,'Se destruída junto de outro Carniçal, retorne uma carta do seu cemitério à mão.'),
(11,'Elemental',2500,500,3,'Cancele o dano se for atacada por uma carta M&F.'),
(12,'Troll',2500,500,2,'Descarte toda a sua mão para comprar duas cartas.'),
(13,'Berseker',1,1,0,'Copie a vida e o poder de uma carta aleatória do cemitério inimigo.'),
(14,'Gargula',2500,200,2,'Bloqueie o ataque inimigo se ele tiver apenas uma carta atacante.'),
(15,'Puero',1700,200,3,'Destrua aleatoriamente uma lendária de qualquer lado do campo.'),
(16,'Necroso',3000,0,2,'Quando destruída como reforço ou vida, destrua uma carta aleatória da mão inimiga com poder menor que a vida desta carta.'),
(17,'Fada',1500,500,2,'Compre uma carta adicional no início de cada turno enquanto permanecer em campo.'),
(18,'Shani',3000,50,4,'Ao ser destruída, ocupe aleatoriamente um slot de vida com carta de vida menor e volte com vida cheia.'),
(19,'Barghest',2000,2000,2,'Se destruída por ataque de poder igual ou maior a três vezes sua vida, retorne ao deck.'),
(20,'Barroso',1300,900,0,'Se descartada, destruída ou roubada da mão por efeito, descarte toda a mão adversária.'),
(21,'Carniçal Atroz',3000,1200,3,'Se sobreviver a um ataque como reforço, compre uma carta épica do deck.'),
(22,'Pantera',1800,1300,4,'Ataque diretamente uma Carta de Vida se sua mão for maior que a mão adversária.'),
(23,'Rei dos Mendigos',1,1450,0,'Destrua uma Carta de Vida inimiga se esta for a única carta em sua mão.'),
(24,'Cutelo',250,2200,0,'Descarte 3 cartas da mão para permitir um ataque direto.'),
(25,'Lugos Todo Roxo',500,500,0,'Dobre permanentemente o poder da próxima carta Civil comprada.'),
(26,'Nekker',2500,1000,2,'Quando destruída, ganhe 1 mana no próximo turno se houver outro Nekker no deck.'),
(27,'Afogador',800,350,0,'Quando destruída como reforço, envie uma carta do deck inimigo ao cemitério.'),
(28,'Lobo',1,1000,0,'Ao atingir uma Carta de Vida, dobre o poder de todos os outros Lobos do seu deck.'),
(29,'Urso',2000,0,2,'Se sobreviver como reforço, dobre sua vida e substitua uma Carta de Vida com menos vida.'),
(30,'Winkler Vosgad',1450,1700,4,'Remova o efeito de uma carta Elfica no campo adversário.'),
(31,'Baltazar',3000,0,3,'Cancele um ataque direto descartando uma carta da mão.'),
(32,'General da Ordem',2000,1700,3,'Se destruída como reforço junto de uma Civil, reduza a mana máxima inimiga em 1 permanentemente.'),
(33,'Totem',1,0,0,'Ao ser destruído com ao menos 3 outros Totens no cemitério, leve todos os Liches e Liches Anciãos do deck à mão com custo 0.'),
(34,'Dilion Vorgues',2000,1500,4,'Reduza em 1 o custo de mana das cartas ainda no seu deck.'),
(35,'Reynold Longmes',2000,0,1,'Puxe um Anão do deck para atacar uma Carta de Vida aleatória; se não destruir, bana os outros Reynold Longmes do deck.'),
(36,'Tamara Stranger',2600,500,4,'Escolha e compre uma carta rara do seu deck.'),
(37,'Jarl de An Skellige',2100,2000,3,'Enquanto ativada como Carta de Vida, efeitos de lendárias não podem ser ativados.'),
(38,'Halmar de Skellige',1300,1700,0,'Ataque uma Carta de Vida inimiga; há 45% de chance de atacar duas Cartas de Vida próprias aleatórias.'),
(39,'Dudu Biberveld',1000,1000,0,'Copie o efeito de uma carta aleatória da mão adversária com custo aumentado em 2.'),
(40,'Thaler',1500,1600,1,'Roube uma carta do deck adversário e adicione-a ao seu cemitério.'),
(41,'Vimme Vivaldi',2500,1200,1,'Cada jogador escolhe uma carta do próprio deck para comprar com custo aumentado em 2.'),
(42,'Casimir Bassi',1200,1800,4,'Destrua uma Carta de Vida inimiga se o deck adversário tiver menos cartas.'),
(43,'Hattori o Elfo Ferreiro',2200,1700,3,'Descarte uma carta aleatória da sua mão e reduza seu custo da próxima carta comprada.'),
(44,'Milton de Peyrac-Peyran',1500,1500,0,'Ao ativar, esta carta retorna à mão no fim do turno.'),
(45,'Síle de Tansarville',2200,0,3,'Compre do deck sua carta M&F de maior custo de mana.'),
(46,'Gaetan',1200,1700,3,'Descarte toda a mão inimiga se esta carta destruir sozinha uma Witcher.'),
(47,'Tomira',3000,0,4,'Restaure completamente uma Carta de Vida aliada danificada.'),
(48,'Ves',2000,2000,3,'Ataque diretamente um alvo aleatório se for a única carta com mana maior que zero na sua mão.'),
(49,'Kiyan – Bruxo da Escola do Gato',1250,1400,2,'Ao ser destruída como reforço ou vida, proteja uma M&F aleatória do deck contra alteração ou cancelamento de mana e efeito.'),
(50,'Corine',2200,700,2,'Veja uma carta aleatória da mão adversária.'),
(51,'Guillaume',1400,1800,0,'Ao destruir sozinho em ataque, destrua uma comum ou rara do deck adversário.'),
(52,'Anabelle',2500,2000,5,'Transforme todas as cartas das duas mãos em Aparição Noturna.'),
(53,'Vlodimir von Everec',1200,1000,2,'Substitua a Carta de Vida de maior raridade de cada lado pela carta de menor raridade do respectivo deck.'),
(54,'Joachim von Gratz-Vampiro',1900,1900,2,'Quando em vida, retorne aleatoriamente uma épica do seu cemitério à mão.'),
(55,'Gerd da Escola do Urso',2000,1600,2,'Quando em vida, dobre sua vida se o adversário já tiver passado um turno.'),
(56,'Cão Selvagem',500,1300,1,'Ataque diretamente uma Carta de Vida escolhida se você possuir uma Carta de Vida Bestiário ativa.'),
(57,'Harpia',100,200,3,'Some o poder das Harpias do deck a esta carta e ataque a Carta de Vida inimiga mais distante.'),
(58,'Vaca',1000,100,3,'Quando destruída como reforço, leve Chorabashe do deck ou cemitério à mão.'),
(59,'Ciri criança',1000,1500,15,'Ataque todas as Cartas de Vida inimigas; custa 1 a menos por Witcher no seu deck.'),
(60,'Barnabas o Mordomo',2000,50,0,'Se você já perdeu uma Carta de Vida, compre uma carta.'),
(61,'Eveline Gallo',1200,1400,5,'Roube a carta de maior custo de mana da mão adversária.'),
(62,'Nenneke Sacerdotisa de Melitele',2500,1000,4,'Roube 1000 de vida de uma Carta de Vida inimiga aleatória e cure uma aliada aleatória; falha sem efeito se o alvo não puder sobreviver.'),
(63,'Carpeado',1600,1000,4,'As cartas das duas mãos custam 0 até o próximo turno de cada jogador.'),
(64,'Marlene de Trastamara',1,0,2,'Transforme-se completamente em um Bestiário aleatório do cemitério inimigo quando ativada da mão ou como vida.'),
(65,'Anna Strenger',1600,800,2,'Aumente em 1 o custo de todas as cartas nas duas mãos.'),
(66,'Skjall',1700,2000,0,'Enquanto no deck, seja destruída no lugar de uma carta Ciri e retorne a Ciri à mão.'),
(67,'Morkvarg',1,0,4,'Quando destruída, ocupe a mão adversária sem poder ser jogada, descartada ou reativada; limite 4, excedentes vão ao cemitério.'),
(68,'Udalryk o Atormentado',800,1700,0,'Descarte uma carta da mão adversária; há 35% de chance de esta carta ocupar uma Carta de Vida própria.'),
(69,'Ida Emean',2000,1300,4,'Veja as duas próximas cartas do deck adversário.'),
(70,'Mestre da Arena',1600,2300,6,'Se não houver reforços inimigos, destrua uma Carta de Vida comum adversária.'),
(71,'Feiticeira Mabel',1400,1800,2,'Destrua aleatoriamente uma Witcher no campo adversário.')
), upserted as (
insert into public.cards(set_id,code,name,image_url,element,rarity,card_type,is_golden,is_original_rpg,base_power,base_max_life,effect_mana_cost,tier,leader_cooldown,effect_text,lore_text,is_active,version)
select s.id,'COMMON_'||lpad(source.n::text,3,'0'),source.name,'https://i.pinimg.com/1200x/71/9a/6b/719a6b3882ba11d72c52f194eaf32af2.jpg','Cívil','common','normal',false,source.n in (30,31,32,34,35,71),source.power,source.life,source.mana,1,0,source.effect_text,null,true,1
from source cross join public.card_sets s where s.code='OFIERI_COMMON'
on conflict(code) do update set name=excluded.name,image_url=excluded.image_url,element=excluded.element,rarity=excluded.rarity,card_type=excluded.card_type,is_original_rpg=excluded.is_original_rpg,base_power=excluded.base_power,base_max_life=excluded.base_max_life,effect_mana_cost=excluded.effect_mana_cost,effect_text=excluded.effect_text,is_active=true,updated_at=now()
returning id,code)
select count(*) from upserted;
