-- Definições versionadas. Cada código COMMON_* é resolvido pelo executor especializado.
with defs(n,trigger_type,effect_code,target_mode,params,is_reaction,once_per_turn) as (values
(0,'passive','common_block_draw_in_hand','self','{}'::jsonb,false,false),
(1,'on_discard','common_draw_three_common','none','{"amount":3,"rarity":"common"}',false,false),
(2,'passive','common_graveyard_return_lock','none','{}',false,false),
(3,'on_attack_declared','common_javali_attack_rules','selected','{"require_nonempty_all_common_hand":true,"suppress_reinforcement_reaction":true}',false,false),
(4,'manual','common_erinia_exchange','selected','{}',false,true),
(5,'manual','common_endriuga_scaled_damage','selected','{"amount_per_reinforcement":500,"mana_cost":2}',false,true),
(6,'manual','common_henselt_attack_all_life','all_enemies','{"mana_cost":7,"requires_enemy_reinforcement_count":0,"maximum_targets":3}',false,true),
(7,'on_attack_declared','common_day_wraith_direct_attack','enemy_random','{"mana_cost":2,"minimum_graveyard_count":5,"ignore_reinforcement":true}',false,false),
(8,'on_destroyed','common_night_wraith_silence_hand','enemy_random','{"required_old_zone":"reinforcement","mana_cost":1}',true,true),
(9,'on_destroyed','common_keira_replace_life','deck','{"required_old_zone":"life","rarity":"common","mana_cost":3}',false,true),
(10,'on_destroyed','common_ghoul_group_revive','graveyard','{"same_name_destroyed":2,"mana_cost":2}',false,true),
(11,'reaction','common_elemental_prevent_damage','self','{"attacker_element":"M&F","mana_cost":3}',true,true),
(12,'manual','common_troll_discard_draw','none','{"draw":2,"mana_cost":2}',false,true),
(13,'manual','common_berserker_copy_stats','graveyard','{}',false,true),
(14,'reaction','common_gargoyle_cancel_single_attack','self','{"attacker_count":1,"mana_cost":2}',true,true),
(15,'manual','common_puero_destroy_random_legendary','enemy_random','{"rarity":"legendary","both_sides":true,"mana_cost":3}',false,true),
(16,'on_destroyed','common_necrophage_destroy_hand','enemy_random','{"old_zones":["reinforcement","life"],"power_below_source_life":true,"mana_cost":2}',false,true),
(17,'on_turn_start','common_fairy_extra_draw','none','{"amount":1,"mana_cost":2}',false,false),
(18,'on_destroyed','common_shani_redeploy_life','self','{"random_eligible_slot":true,"restore_full_life":true,"mana_cost":4}',false,true),
(19,'on_destroyed','common_barghest_overkill_to_deck','self','{"minimum_overkill_ratio":3,"mana_cost":2}',false,true),
(20,'on_discard','common_barroso_purge_enemy_hand','all_enemies','{"also_trigger_on_stolen_or_destroyed_from_hand":true}',false,false),
(21,'on_attack_resolved','common_atrocious_ghoul_draw_epic','none','{"required_zone":"reinforcement","must_survive":true,"rarity":"epic","mana_cost":3}',false,true),
(22,'on_attack_declared','common_panther_direct_life','selected','{"requires_hand_advantage":true,"mana_cost":4,"ignore_reinforcement":true}',false,false),
(23,'manual','common_beggar_king_destroy_life','selected','{"require_only_card_in_hand":true}',false,true),
(24,'on_attack_declared','common_cleaver_discard_for_direct','selected','{"discard_cost":3,"ignore_reinforcement":true}',false,false),
(25,'manual','common_lugos_next_civil_double_power','none','{"element":"Cívil","multiplier":2}',false,true),
(26,'on_destroyed','common_nekker_next_turn_mana','none','{"deck_name":"Nekker","amount":1,"mana_cost":2}',false,true),
(27,'on_destroyed','common_drowner_mill','deck','{"required_old_zone":"reinforcement","amount":1}',false,false),
(28,'on_attack_resolved','common_wolf_buff_deck','deck','{"target_name":"Lobo","multiplier":2,"requires_life_hit":true}',false,false),
(29,'on_attack_resolved','common_bear_promote_to_life','self','{"required_zone":"reinforcement","must_survive":true,"life_multiplier":2,"mana_cost":2}',false,true),
(30,'manual','common_winkler_silence_elf','selected','{"element":"Elfica","mana_cost":4}',false,true),
(31,'reaction','common_baltazar_cancel_direct','none','{"discard_cost":1,"mana_cost":3}',true,true),
(32,'on_destroyed','common_general_reduce_max_mana','enemy','{"required_old_zone":"reinforcement","simultaneous_element":"Cívil","amount":-1,"mana_cost":3}',false,true),
(33,'on_destroyed','common_totem_tutor_liches','deck','{"graveyard_same_name_minimum":4,"names":["Liche","Liche Ancião"],"mana_override":0}',false,true),
(34,'manual','common_dilion_reduce_deck_cost','deck','{"amount":-1,"mana_cost":4}',false,true),
(35,'manual','common_reynold_forced_dwarf_attack','deck','{"element_or_tag":"Anão","failure_ban_name":"Reynold Longmes","mana_cost":1}',false,true),
(36,'manual','common_tamara_choose_rare','deck','{"rarity":"rare","mana_cost":4,"player_choice":true}',false,true),
(37,'manual','common_jarl_lock_legendary_effects','none','{"required_zone":"life","rarity":"legendary","mana_cost":3}',false,true),
(38,'manual','common_halmar_coin_attack','enemy_random','{"enemy_chance":55,"self_chance":45,"self_targets":2}',false,true),
(39,'manual','common_dudu_copy_hand_effect','enemy_random','{"copied_cost_delta":2}',false,true),
(40,'manual','common_thaler_steal_deck_to_graveyard','deck','{"mana_cost":1}',false,true),
(41,'manual','common_vivaldi_mutual_tutor','deck','{"cost_delta":2,"mana_cost":1,"choice_both_players":true}',false,true),
(42,'manual','common_casimir_destroy_life','selected','{"requires_enemy_deck_smaller":true,"mana_cost":4}',false,true),
(43,'manual','common_hattori_discard_next_discount','none','{"random_discard":1,"discount_equals_discarded_cost":true,"mana_cost":3}',false,true),
(44,'manual','common_milton_return_turn_end','self','{}',false,true),
(45,'manual','common_sile_tutor_highest_mana','deck','{"element":"M&F","mana_cost":3}',false,true),
(46,'on_attack_resolved','common_gaetan_purge_hand','enemy','{"destroyed_alone":true,"target_element":"Witcher","mana_cost":3}',false,true),
(47,'manual','common_tomira_full_heal','ally','{"required_zone":"life","restore_to_maximum":true,"mana_cost":4}',false,true),
(48,'on_attack_declared','common_ves_direct_random','enemy_random','{"only_positive_mana_card_in_hand":true,"mana_cost":3,"ignore_reinforcement":true}',false,false),
(49,'on_destroyed','common_kiyan_protect_deck_card','deck','{"old_zones":["reinforcement","life"],"element":"M&F","protect_mana_and_effect":true,"mana_cost":2}',true,true),
(50,'manual','common_corine_peek_hand','enemy_random','{"mana_cost":2,"private_reveal_seconds":30}',false,true),
(51,'on_attack_resolved','common_guillaume_destroy_deck','deck','{"destroyed_alone":true,"rarities":["common","rare"]}',false,false),
(52,'manual','common_anabelle_transform_hands','all_allies','{"target_card_name":"Aparição Noturna","both_players":true,"mana_cost":5}',false,true),
(53,'manual','common_vlodimir_replace_highest_life','deck','{"both_players":true,"life_selector":"highest_rarity","deck_selector":"lowest_rarity","mana_cost":2}',false,true),
(54,'manual','common_joachim_revive_epic','graveyard','{"required_zone":"life","rarity":"epic","random":true,"mana_cost":2}',false,true),
(55,'manual','common_gerd_double_life','self','{"required_zone":"life","opponent_ever_passed":true,"multiplier":2,"mana_cost":2}',false,true),
(56,'on_attack_declared','common_wild_dog_direct_life','selected','{"requires_active_life_element":"Bestiário","mana_cost":1,"ignore_reinforcement":true}',false,false),
(57,'manual','common_harpy_absorb_and_attack','enemy','{"deck_name":"Harpia","target_life_position":"farthest","mana_cost":3,"ignore_reinforcement":true}',false,true),
(58,'on_destroyed','common_cow_tutor_chorabashe','deck','{"required_old_zone":"reinforcement","target_name":"Chorabashe","zones":["deck","graveyard"],"mana_cost":3}',false,true),
(59,'manual','common_child_ciri_attack_all_life','all_enemies','{"base_mana_cost":15,"discount_per_deck_element":"Witcher","discount_amount":1}',false,true),
(60,'manual','common_barnabas_draw','none','{"requires_life_ever_destroyed":true,"amount":1}',false,true),
(61,'manual','common_eveline_steal_highest_mana','hand','{"mana_cost":5}',false,true),
(62,'manual','common_nenneke_nonlethal_steal','enemy_random','{"amount":1000,"must_leave_target_life":1,"heal_random_ally_life":true,"mana_cost":4}',false,true),
(63,'manual','common_carpeado_zero_hand_costs','all_allies','{"both_players":true,"mana_override":0,"expires_on_each_next_turn":true,"mana_cost":4}',false,true),
(64,'manual','common_marlene_transform','graveyard','{"allowed_source_zones":["hand","life"],"target_element":"Bestiário","copy_all":true,"mana_cost":2}',false,true),
(65,'manual','common_anna_increase_hand_costs','all_allies','{"both_players":true,"amount":1,"mana_cost":2}',false,true),
(66,'passive','common_skjall_substitute_ciri','deck','{"protected_name_contains":"Ciri","move_protected_to":"hand","move_source_to":"graveyard"}',false,false),
(67,'on_destroyed','common_morkvarg_curse_hand','enemy','{"maximum_in_enemy_hand":4,"overflow_zone":"graveyard","unplayable":true,"undiscardable":true,"mana_cost":4}',false,true),
(68,'manual','common_udalryk_discard_coin_life','enemy_random','{"self_to_life_chance":35}',false,true),
(69,'manual','common_ida_peek_deck','deck','{"amount":2,"mana_cost":4,"private_reveal_seconds":30}',false,true),
(70,'manual','common_arena_master_destroy_life','enemy_random','{"requires_enemy_reinforcement_count":0,"rarity":"common","mana_cost":6}',false,true),
(71,'manual','common_mabel_destroy_witcher','enemy_random','{"element":"Witcher","mana_cost":2}',false,true)
)
insert into public.card_effects(card_id,effect_order,trigger_type,effect_code,target_mode,parameters,priority,is_reaction,once_per_turn,is_active)
select c.id,1,d.trigger_type,d.effect_code,d.target_mode,d.params,0,d.is_reaction,d.once_per_turn,true
from defs d join public.cards c on c.code='COMMON_'||lpad(d.n::text,3,'0')
on conflict(card_id,effect_order) do update set trigger_type=excluded.trigger_type,effect_code=excluded.effect_code,target_mode=excluded.target_mode,parameters=excluded.parameters,is_reaction=excluded.is_reaction,once_per_turn=excluded.once_per_turn,is_active=true,updated_at=now();
