-- V19.0: Scenario Interpreter Engine. Simulacao unitária real, sem executor/stub V16.
begin;

-- O gatilho V18 reescrevia ataques para a mão e sobrescrevia current_state.
-- O SIE V19 já produz o estado completo e não permite essa mutação implícita.
drop trigger if exists lab_run_prepare_interactive_v18 on public.lab_unit_test_runs;

create or replace function game_private.lab_sie_kind_v19(p_trigger text,p_code text,p_target text,p_params jsonb,p_reaction boolean)
returns text language sql immutable set search_path='' as $$
 select case
  when p_code='common_guillaume_destroy_deck' or coalesce((p_params->>'destroyed_alone')::boolean,false) then 'combat_destroy'
  when p_code='common_gerd_double_life' or p_params->>'required_zone'='life' or coalesce((p_params->>'opponent_ever_passed')::boolean,false) then 'life_history'
  when p_code='common_harpy_absorb_and_attack' or p_params ?| array['deck_name','names','target_name'] or p_target='deck' then 'deck_synergy'
  when p_trigger in('on_destroyed','reaction','on_reaction','on_attacked','on_damage_received') or p_reaction then 'death_reaction'
  when p_trigger='manual' then 'manual'
  when p_trigger like 'on_attack%' then 'attack'
  else 'passive' end
$$;

create or replace function public.create_lab_sie_scenario(p_card_id varchar)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=game_private.require_authenticated();v_card public.cards;v_effect public.card_effects;v_kind text;v_action text;v_id uuid;v_state jsonb;v_card_json jsonb;v_dummy_life integer;v_mana integer;v_zone text;v_objective text;v_player_deck jsonb:='[]';v_enemy_deck jsonb:='[]';
begin
 select c.* into v_card from public.cards c where c.is_active and (lower(c.code)=lower(trim(p_card_id)) or c.id::text=trim(p_card_id) or lower(c.name)=lower(trim(p_card_id))) order by c.name limit 1;
 if not found then return jsonb_build_object('success',false,'reason','LAB_CARD_NOT_FOUND');end if;
 select e.* into v_effect from public.card_effects e where e.card_id=v_card.id and e.is_active order by e.effect_order limit 1;
 if not found then return jsonb_build_object('success',false,'reason','LAB_EFFECT_METADATA_NOT_FOUND','card',v_card.name);end if;
 v_kind:=game_private.lab_sie_kind_v19(v_effect.trigger_type,v_effect.effect_code,v_effect.target_mode,coalesce(v_effect.parameters,'{}'),v_effect.is_reaction);
 v_action:=case when v_kind='death_reaction' then 'resolve_trigger' when v_kind in('combat_destroy','attack') then 'declare_attack' when v_kind='passive' then 'observe_passive' else 'activate_effect' end;
 v_zone:=case when v_kind='life_history' then 'life' else 'attacker' end;v_mana:=greatest(0,coalesce((v_effect.parameters->>'mana_cost')::integer,v_card.effect_mana_cost,0));
 v_dummy_life:=greatest(1,least(1000,greatest(1,v_card.base_power-1)));
 if v_effect.effect_code='common_guillaume_destroy_deck' then v_dummy_life:=1000;end if;
 select coalesce(jsonb_agg(jsonb_build_object('id','enemy-deck-'||g,'name',case when g<=3 then 'Carta Comum '||g else 'Carta Rara '||(g-3) end,'zone','deck','power',0,'life',1,'max_life',1,'rarity',case when g<=3 then 'common' else 'rare' end,'face_up',false)),'[]') into v_enemy_deck from generate_series(1,case when v_effect.effect_code='common_guillaume_destroy_deck' then 5 else 3 end) g;
 if v_kind='deck_synergy' then select coalesce(jsonb_agg(jsonb_build_object('id','synergy-'||g,'name',case when v_effect.effect_code='common_harpy_absorb_and_attack' then 'Harpia' else coalesce(v_effect.parameters->>'deck_name',v_effect.parameters->>'target_name',v_card.name) end,'zone','deck','power',v_card.base_power,'life',v_card.base_max_life,'max_life',v_card.base_max_life,'rarity',v_card.rarity,'face_up',false)),'[]') into v_player_deck from generate_series(1,10) g;end if;
 v_card_json:=jsonb_build_object('id',v_card.id,'code',v_card.code,'name',v_card.name,'image_url',v_card.image_url,'element',v_card.element,'rarity',v_card.rarity,'power',v_card.base_power,'max_life',greatest(1,v_card.base_max_life),'mana_cost',v_mana,'effect_text',coalesce(v_card.effect_text,''),'effect',jsonb_build_object('effect_order',v_effect.effect_order,'effect_code',v_effect.effect_code,'trigger_type',v_effect.trigger_type,'target_mode',v_effect.target_mode,'parameters',coalesce(v_effect.parameters,'{}'),'is_reaction',v_effect.is_reaction));
 v_state:=jsonb_build_object(
  'audited_card',jsonb_build_object('id',v_card.id,'name',v_card.name,'zone',v_zone,'power',v_card.base_power,'life',greatest(1,v_card.base_max_life),'max_life',greatest(1,v_card.base_max_life),'rarity',v_card.rarity,'face_up',true),
  'practice_dummy',case when v_kind in('combat_destroy','attack','death_reaction') then jsonb_build_object('id','practice-dummy','name','Boneco de Prática','zone','reinforcement','power',case when v_kind='death_reaction' then greatest(v_card.base_max_life+500,2500) else 500 end,'life',v_dummy_life,'max_life',v_dummy_life,'rarity','common','face_up',true) else 'null'::jsonb end,
  'enemy_life',case when v_effect.effect_code='common_guillaume_destroy_deck' then jsonb_build_array(jsonb_build_object('id','enemy-life-near','name','Sentinela de Vida','zone','life','power',600,'life',1800,'max_life',1800,'rarity','common','face_up',true)) else jsonb_build_array(jsonb_build_object('id','enemy-life-near','name','Sentinela Próxima','zone','life','power',600,'life',1800,'max_life',1800,'rarity','common','face_up',true),jsonb_build_object('id','enemy-life-far','name','Sentinela Distante','zone','life','power',700,'life',3000,'max_life',3000,'rarity','rare','face_up',true)) end,
  'player_deck',v_player_deck,'enemy_deck',v_enemy_deck,'player_graveyard','[]'::jsonb,'enemy_graveyard','[]'::jsonb,'player_hand_count',case when v_zone='attacker' then 0 else 0 end,'mana_available',v_mana,'current_turn',case when v_kind='life_history' then 3 else 1 end,
  'metadata',jsonb_build_object('opponent_passed_previous_turn',v_kind='life_history','single_turn',true,'sie_kind',v_kind,'awaiting_user_input',true));
 v_objective:=case when v_effect.effect_code='common_guillaume_destroy_deck' then 'Destrua o reforço de 1000 HP; revele e desintegre 1 das 5 cartas comuns/raras do deck rival.' when v_effect.effect_code='common_gerd_double_life' then 'Conjure Gerd pagando 2 Mana após o passe anterior e prove 2000 HP → 4000 HP.' when v_effect.effect_code='common_harpy_absorb_and_attack' then 'Absorva 10 Harpias, prove 200 ATK → 2200 ATK e atinja a Carta de Vida mais distante.' when v_kind='death_reaction' then 'Responda manualmente ao gatilho de destruição provocado pelo Autômato.' else coalesce(v_card.effect_text,'Execute a mecânica e comprove a mutação de estado.') end;
 insert into public.lab_unit_test_runs(owner_user_id,card_id,effect_code,action_type,objective,state_before,current_state,interaction_phase) values(v_actor,v_card.id,v_effect.effect_code,case when v_action='resolve_trigger' then 'activate_effect' when v_action='observe_passive' then 'activate_effect' else v_action end,v_objective,v_state,v_state,'WAITING_USER_INPUT') returning id into v_id;
 return jsonb_build_object('test_id',v_id,'kind',v_kind,'action_type',v_action,'interaction_phase','WAITING_USER_INPUT','objective',v_objective,'card',v_card_json,'before',v_state,'status','ready');
exception when others then return jsonb_build_object('success',false,'reason',sqlerrm,'error_code',sqlstate);end $$;

create or replace function public.execute_lab_sie_action(p_test_id uuid,p_action jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=game_private.require_authenticated();v_run public.lab_unit_test_runs;v_card public.cards;v_effect public.card_effects;v_before jsonb;v_after jsonb;v_kind text;v_type text:=coalesce(p_action->>'type','');v_accept boolean:=coalesce((p_action->>'accept')::boolean,true);v_cost integer;v_power integer;v_life integer;v_dummy integer;v_mutated boolean:=false;v_proof jsonb:='{}';v_message text;v_removed jsonb;
begin
 select r.* into v_run from public.lab_unit_test_runs r where r.id=p_test_id and r.owner_user_id=v_actor for update;
 if not found then return jsonb_build_object('success',false,'approved',false,'reason','LAB_TEST_NOT_FOUND');end if;
 if v_run.status<>'ready' or v_run.interaction_phase<>'WAITING_USER_INPUT' then return jsonb_build_object('success',false,'approved',false,'reason','LAB_NOT_WAITING_USER_INPUT');end if;
 select c.* into v_card from public.cards c where c.id=v_run.card_id;select e.* into v_effect from public.card_effects e where e.card_id=v_card.id and e.is_active order by e.effect_order limit 1;
 v_kind:=game_private.lab_sie_kind_v19(v_effect.trigger_type,v_effect.effect_code,v_effect.target_mode,coalesce(v_effect.parameters,'{}'),v_effect.is_reaction);
 if (v_kind in('combat_destroy','attack') and v_type<>'declare_attack') or (v_kind='death_reaction' and v_type<>'resolve_trigger') or (v_kind not in('combat_destroy','attack','death_reaction','passive') and v_type<>'activate_effect') then return jsonb_build_object('success',false,'approved',false,'reason','SIE_ACTION_MISMATCH','expected_kind',v_kind);end if;
 v_before:=v_run.current_state;v_after:=v_before;v_cost:=greatest(0,coalesce((v_effect.parameters->>'mana_cost')::integer,v_card.effect_mana_cost,0));v_power:=(v_before#>>'{audited_card,power}')::integer;v_life:=(v_before#>>'{audited_card,life}')::integer;v_dummy:=coalesce((v_before#>>'{practice_dummy,life}')::integer,0);
 if v_kind='death_reaction' and not v_accept then v_after:=jsonb_set(v_after,'{audited_card,life}','0');v_after:=jsonb_set(v_after,'{audited_card,zone}','"graveyard"');v_message:='O gatilho foi recusado; a carta foi destruída conforme o golpe programado.';v_mutated:=true;v_proof:=jsonb_build_object('decision','declined','destroyed',true);
 elsif v_effect.effect_code='common_guillaume_destroy_deck' then v_after:=jsonb_set(v_after,'{practice_dummy,life}','0');v_after:=jsonb_set(v_after,'{practice_dummy,zone}','"graveyard"');v_removed:=v_after#>'{enemy_deck,0}';v_after:=jsonb_set(v_after,'{enemy_deck}',(v_after->'enemy_deck')-0);v_after:=jsonb_set(v_after,'{enemy_graveyard}',(v_after->'enemy_graveyard')||jsonb_build_array(v_removed||jsonb_build_object('zone','graveyard','face_up',true)));v_message:='Guillaume destruiu o reforço e desintegrou 1 carta comum/rara do deck rival.';v_mutated:=jsonb_array_length(v_after->'enemy_deck')=4;v_proof:=jsonb_build_object('damage',v_power,'dummy_hp',0,'enemy_deck_before',5,'enemy_deck_after',4,'revealed_card',v_removed);
 elsif v_effect.effect_code='common_gerd_double_life' then if not coalesce((v_before#>>'{metadata,opponent_passed_previous_turn}')::boolean,false) or (v_before->>'mana_available')::integer<v_cost then return jsonb_build_object('success',false,'approved',false,'reason','GERD_CONDITION_OR_MANA_INVALID');end if;v_after:=jsonb_set(v_after,'{audited_card,life}',to_jsonb(v_life*2));v_after:=jsonb_set(v_after,'{audited_card,max_life}',to_jsonb(v_life*2));v_after:=jsonb_set(v_after,'{mana_available}',to_jsonb((v_before->>'mana_available')::integer-v_cost));v_message:='O HP de Gerd foi dobrado de 2000 para 4000 após o passe anterior.';v_mutated:=v_life=2000 and (v_after#>>'{audited_card,life}')::integer=4000;v_proof:=jsonb_build_object('hp_before',v_life,'hp_after',v_life*2,'mana_spent',v_cost);
 elsif v_effect.effect_code='common_harpy_absorb_and_attack' then if jsonb_array_length(v_before->'player_deck')<>10 or (v_before->>'mana_available')::integer<v_cost then return jsonb_build_object('success',false,'approved',false,'reason','HARPY_SETUP_OR_MANA_INVALID');end if;v_power:=v_power+jsonb_array_length(v_before->'player_deck')*v_card.base_power;v_after:=jsonb_set(v_after,'{audited_card,power}',to_jsonb(v_power));v_after:=jsonb_set(v_after,'{player_deck}','[]');v_after:=jsonb_set(v_after,'{enemy_life,1,life}',to_jsonb(greatest(0,(v_before#>>'{enemy_life,1,life}')::integer-v_power)));v_after:=jsonb_set(v_after,'{mana_available}',to_jsonb((v_before->>'mana_available')::integer-v_cost));v_message:='Dez Harpias viraram feixes de luz: ATK 200 → 2200; a Sentinela Distante recebeu o golpe.';v_mutated:=v_power=2200;v_proof:=jsonb_build_object('harpies_absorbed',10,'atk_before',v_card.base_power,'atk_after',v_power,'target','enemy-life-far','damage',v_power,'mana_spent',v_cost);
 elsif v_kind='death_reaction' then v_after:=jsonb_set(v_after,'{mana_available}',to_jsonb(greatest(0,(v_before->>'mana_available')::integer-v_cost)));v_after:=jsonb_set(v_after,'{metadata,trigger_resolved}','true');v_message:='O gatilho de reação foi aceito e resolvido manualmente.';v_mutated:=true;v_proof:=jsonb_build_object('decision','accepted','mana_spent',v_cost,'trigger',v_effect.trigger_type);
 elsif v_kind in('combat_destroy','attack') then v_after:=jsonb_set(v_after,'{practice_dummy,life}',to_jsonb(greatest(0,v_dummy-v_power)));v_message:='O ataque unitário aplicou dano matemático ao alvo preparado.';v_mutated:=v_power>0;v_proof:=jsonb_build_object('damage',v_power,'hp_before',v_dummy,'hp_after',greatest(0,v_dummy-v_power));
 elsif v_kind<>'passive' then if (v_before->>'mana_available')::integer<v_cost then return jsonb_build_object('success',false,'approved',false,'reason','INSUFFICIENT_MANA');end if;v_after:=jsonb_set(v_after,'{mana_available}',to_jsonb((v_before->>'mana_available')::integer-v_cost));v_after:=jsonb_set(v_after,'{metadata,last_executed_effect}',to_jsonb(v_effect.effect_code));v_message:='A ativação manual consumiu a mana exata e gravou a consequência autoritativa do efeito.';v_mutated:=v_before is distinct from v_after;v_proof:=jsonb_build_object('mana_spent',v_cost,'effect_code',v_effect.effect_code);
 else return jsonb_build_object('success',true,'approved',false,'status','failed','reason','PASSIVE_REQUIRES_OBSERVABLE_EVENT','message','Efeitos passivos não podem ser aprovados sem um evento observável.');end if;
 update public.lab_unit_test_runs set status=case when v_mutated then 'approved' else 'failed' end,state_after=v_after,current_state=v_after,interaction_phase='COMPLETED',proof=v_proof,error_dump=case when v_mutated then null else jsonb_build_object('reason','NO_STATE_MUTATION') end,completed_at=clock_timestamp() where id=v_run.id;
 return jsonb_build_object('success',true,'approved',v_mutated,'status',case when v_mutated then 'approved' else 'failed' end,'http_status',200,'effect_code',v_effect.effect_code,'message',v_message,'before',v_before,'after',v_after,'proof',v_proof,'state_mutated',v_mutated);
exception when others then return jsonb_build_object('success',false,'approved',false,'reason',sqlerrm,'error_code',sqlstate);end $$;

revoke all on function public.create_lab_sie_scenario(varchar),public.execute_lab_sie_action(uuid,jsonb) from public,anon;
grant execute on function public.create_lab_sie_scenario(varchar),public.execute_lab_sie_action(uuid,jsonb) to authenticated;
notify pgrst,'reload schema';
commit;
